### ISSUE TITLE
connection timed out 

### ISSUE THREAD

**Issue by elijah0kello** [adrienverge/openfortivpn#1013]
Hello I am trying to connect a remote vpn using openfortivpn but I get the following error when I start the `openfortivpn` system daemon.

```bash
Sep  6 17:21:49 api openfortivpn[1463]: ERROR:  connect: Connection timed out
Sep  6 17:21:49 api openfortivpn[1463]: INFO:   Closed connection to gateway.
Sep  6 17:24:00 api openfortivpn[1463]: ERROR:  connect: Connection timed out
Sep  6 17:24:00 api openfortivpn[1463]: INFO:   Could not log out.
Sep  6 17:24:05 api systemd[1]: openfortivpn.service: Service hold-off time over, scheduling restart.
Sep  6 17:24:05 api systemd[1]: openfortivpn.service: Scheduled restart job, restart counter is at 5.
Sep  6 17:24:05 api systemd[1]: Stopped OpenFortiVPN Service.
Sep  6 17:24:05 api systemd[1]: Started OpenFortiVPN Service.
```

Please help me know what could be the problem.

**Comment by DimitriPapadopoulos** [comment]
What seems to happen is that the FortiGate closes the connection. Two possible reasons that I can see:
* The VPN tunnel has been idle for too long - not sure what qualifies as "too long" but I seem to recall it depends on the FortiGate parameters.
* You have hit the hard limit of the VPN connection, again it depends on the FortiGate parameters. The default is 8 hours, see [Technical Tip: SSL-VPN connection logout after 8 hours](https://community.fortinet.com/t5/FortiGate/Technical-Tip-SSL-VPN-connection-logout-after-8-hours/ta-p/191322).

I might be wrong in my understanding of the situation though. I don't have enough information and it would help if you could start `openfortivpn` from the command line instead of running it as a daemon - only while debugging. Also how long after starting `openfortivpn` does the connection time out?

**Comment by elijah0kello** [comment]
Even when I start `openfortivpn` from the command line like this. 
```bash 
sudo openfortivpn -c /etc/openfortivpn/config
```
It outputs this after a minute or so

```terminal
connect: Connection timed out
Closed connection to gateway.
```

It just hangs for a few minutes and outputs that. What could I be doing wrong?

**Comment by DimitriPapadopoulos** [comment]
Ah, got it. I thought the VPN would work for some time, perhaps a few hours, and then bail out all of a sudden. But now I understand it doesn't work at all: you start it it and after a minute or so it bails out with the time out message.

Perhaps it would help to have the full (redacted) log of `openfortivpn -v -v`.

Clearly the `connect()` system call fails here:
https://github.com/adrienverge/openfortivpn/blob/fc6c7bd9e97ccc467d3f8c26858f384e2f8159a9/src/tunnel.c#L756-L760

It is called through `ssl_connect()` from `run_tunnel()`, which means `openfortivpn` fails to even establish the tunnel.

Just a few basic questions:
* Are you connecting to a **Fortinet** portal?
* Is the Fortinet portal capable of SSL VPN or only IPSec?
* Are you able to connect to the VPN using the [official client](https://www.fortinet.com/support/product-downloads#vpn)?
* Is the VPN portal reachable from your network? Can you ping it? Can you open it in a web browser?
* What is your exact operating system?

**Comment by DimitriPapadopoulos** [comment]
Have you been able to connect?

**Comment by wildborn** [comment]
Hi Dimitri 
I'm facing same problem with the client as I call openfortivpn it freezes the screen and now its showing the message mentioned below please suggest me it's resolution.

`ERROR:  connect: Connection timed out
INFO:   Closed connection to gateway.
ERROR:  connect: Connection timed out
INFO:   Could not log out.
ERROR:  connect: Connection timed out
INFO:   Closed connection to gateway.
ERROR:  connect: Connection timed out
INFO:   Could not log out.
ERROR:  connect: Connection timed out
INFO:   Closed connection to gateway.
ERROR:  connect: Connection timed out
INFO:   Could not log out.
ERROR:  connect: Connection timed out
INFO:   Closed connection to gateway.
`

**Comment by DimitriPapadopoulos** [comment]
@wildborn Please open a new issue if needed.
