### ISSUE TITLE
otp commandline parameter

### ISSUE THREAD

**Issue by rexcze** [adrienverge/openfortivpn#104]
Hello,

-o or --opt= switch does nothing.  Output follows:

`openfortivpn <gateway-ip> -u user -p password --opt=123456`
`INFO:   Connected to gateway.`
`2factor authentication token:`

We are using version 1.3.0

**Comment by mrbaseman** [comment]
There are different kinds of 2FA (See #79). Maybe the -o option doesn't work for all of them yet.

**Comment by rexcze** [comment]
This issue appears with fortitoken.

Dne 27. 2. 2017 15:03 napsal uživatel "Martin Hecht" <
notifications@github.com>:

**Comment by digmore** [comment]
I too was confused by the OTP handling. I looked into it and it turns out the "-o" switch was not implemented in the code. I've submitted a PR to fix this.

I notice also that your example says "--opt". If you try changing the spelling to "--otp" you might find it works. I spent a while trying to get the short switch to work, but once I switched to the longer one it worked first time.

**Comment by mrbaseman** [comment]
I have just found this still open. The -o option is recognized in the meantime, and --otp should have worked before if spelled correctly. Can we close this issue?

**Comment by BlueCase** [comment]
I have exactly the same issue as rexcze
```
openfortivpn -vvv --otp=111111
DEBUG:  Loaded config file "/etc/openfortivpn/config".
VPN account password: 
DEBUG:  Config host = "vpn.abc.de"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "lalalala"
DEBUG:  Config password = "********"
DEBUG:  One-time password = "111111"
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
2factor authentication token: 
```

openfortivpn version: 1.5.0 (same with 1.4.0)
Token: FortiToken 200 HW OTP

Have someone a idea what could be the error?

**Comment by DimitriPapadopoulos** [comment]
@BlueCase The original cause of this issue was double:
- `--otp` not implemented but it should be now ()
- use of `--opt` instead of `--otp`

This looks different. The one-time password is taken into account:
`DEBUG:  One-time password = "111111"
`

It would be better to create a new ticket wouldn't it?

**Comment by BlueCase** [comment]
@DimitriPapadopoulos created #170
