### ISSUE TITLE
WSL2: GUI shows empty

### ISSUE THREAD

**Issue by afilp** [adrienverge/openfortivpn#1060]
This is what we see in Windows 10 WSL2, when opening the GUI:

![image](https://user-images.githubusercontent.com/7850073/213306016-c6308e52-4dbc-4c7d-98ff-e4ed73e18911.png)

The GUI is empty.

How can we solve the problem?

**Comment by DimitriPapadopoulos** [comment]
How is this related to ipenfortivpn?

**Comment by DimitriPapadopoulos** [comment]
Note that ipenfortivpn is an open source command line client for Fortinet VPN SSL - no GUI and does **not** run on Windows.

You seem to be using a proprietary FortiClient client on Windows - and most probably the wrong one. Why do you think your question is related to ipenfortivpn?

Also how is WSL2 related to whatever you are showing here?

**Comment by afilp** [comment]
Thanks, I misunderstood.

The Forticlient GUI that I am running in WSL2 is a Unix app, not a Windows app. This is why I mentioned WSL2, the screenshot above is from an app that runs in Ubuntu v20 (my wsl2 distro).

We can close this issue since this is not related to FortiClient (I thought that they are of the same organization).

**Comment by DimitriPapadopoulos** [comment]
FortiClient is proprietary software, you need to talk to Fortinet support, please avoid draining time resources from open source projects.

With that said, you should use the Windows app on Windows, instead of trying to use the Linux app using the WSL2 subsystem. I doubt Fortinet support will be eager to support that use case – but that's their call, and I'll leave you to discuss this issue with them.
