### ISSUE TITLE
on MacOSX pppd may be locked in zombie state

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#133]
in #132 a locking issue was addressed, but the root cause for the locking issue to occur seems to be an instance of pppd which became a zombie process. 
This has only been observed on MacOSX when openfortivpn was launched without elevated privileges.
This issue is a reminder that we should have a deeper look at this topic and try to avoid pppd becoming a zombie.

**Comment by DimitriPapadopoulos** [comment]
A Google search shows few occurrences of stuck _pppd_ processes on MacOS X:
- [Debugging a Stuck pppd Process](https://administratosphere.wordpress.com/2007/08/04/debugging-a-stuck-pppd-process/)
- [Why is the menu bar showing the VPN “Disconnecting” animation forever?](https://apple.stackexchange.com/questions/12894/why-is-the-menu-bar-showing-the-vpn-disconnecting-animation-forever#12911)

**Comment by Mabin-J** [comment]
I found why #132 is issued.

First of all, I'm sorry. 
That issue isn't related by zombie process.

After more test, I found that It is locked when run [io.c#L612](https://github.com/adrienverge/openfortivpn/blob/c3aecd1a053f2325266f240cd32046a35ca029eb/src/io.c#L612).

I think that `pthread_cancel()` is not same with Linux.

I found that `pthread_cancel()` wan't implemented on macOS in past but I don't know this function is implemented now.
(https://discussions.apple.com/thread/268013)

If `pthread_cancel()` is implemented now, `sem_wait` can be caused because `sem_wait` is use `dispatch_semaphore_wait` in macOS. ([io.c#L41](https://github.com/adrienverge/openfortivpn/blob/c3aecd1a053f2325266f240cd32046a35ca029eb/src/io.c#L41))

**Comment by DimitriPapadopoulos** [comment]
Do you mean _pthread_cancel()_ (line 606) or _pthread_join_ (line 612)?

In any case _pthread_cancel()__ does seem to be implemented on Mac OS > 10.2.5 but it seems there have been issues with this implementation over the years. See for example:
[pthread_cancel and cancelation points still broken in Mac OS X 10.5 Leopard?](https://lists.apple.com/archives/darwin-kernel/2007/Nov/msg00104.html)

**Comment by Mabin-J** [comment]
But I think that `pthread_cancel` cannot effect to `dispatch_semaphore_wait`.
It seems that `dispatch_semaphore_wait` not use real semaphore.

**Comment by DimitriPapadopoulos** [comment]
Please bear with me as I haven't programmed with threads for years and I haven't written but a few lines of code on Mac OS. I have googled keywords such as ""Mac OS" posix threads semaphore thread_cancel" and found for example:
- [Mac OS X platform specific pthreads issues](http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__files_GUID_EE052898_C59C_438A_9A77_798F5BEB7A77_htm)

Mac OS X 10.4 Tiger is of course obsolete and Mac OS X 10.5 Leopard was released as soon as October 2007. So I'm not certain the above link is still relevant (although it is part of Autodesk Maya 2017 developer guide:
- Unnamed semaphores are not supported.
- Cancellation points are only `pthread_test_cancel()` instead of POSIX mandatory cancellation points. So `pthread_cancel` will cancel a thread only when `pthread_test_cancel()` is called by that thread. (This is fixed in Leopard.)

**Comment by Mabin-J** [comment]
If `pthread_cancel cannot` effect to `dispatch_semaphore_wait`, `if_config` should be returned at [io.c#L509](https://github.com/adrienverge/openfortivpn/blob/158f4894ed5164991168a66bba874a9a268d4bbb/src/io.c#L509) but it isn't... ;(

**Comment by Mabin-J** [comment]
I tried to use 'semaphore_' series but it didn't works, too.
'semaphore_wait' didn't wait...
:(

**Comment by Mabin-J** [comment]
Sorry. I tried with `semaphore_*` and it was succeed. I mistook about define.

**Comment by mrbaseman** [comment]
can we close this issue? we have #137 for the general discussion about the locking issue now.

**Comment by Mabin-J** [comment]
I think that yes.
