### ISSUE TITLE
Passwords starting with an exclamation mark (!)

### ISSUE THREAD

**Issue by willcurtis** [adrienverge/openfortivpn#146]
When attempting to connect a VPN using a string rather than a config file, if the password starts with an exclamation mark the exclamation is stripped causing it to flag a syntax error

**Comment by DimitriPapadopoulos** [comment]
I am unable to test and reproduce that myself because I don't have a choice of passwords on the VPN I have access to, however:
- I don't see the exclamation mark being processed as a special character in _openfortivpn_, therefore I suspect the problem is elsewhere. More specifically the Unix/Linux shell does interpret the exclamation mark as a special character, so I suspect you might need to "escape" this character if the shell is involved.
- Can you describe what you mean by "_using a string_", so that I can understand whether the shell is involved? Are you using the **`-p`** or **`--password`** option?

**Comment by DimitriPapadopoulos** [comment]
Fell free to re-open if you believe this is really an issue with _openfortivpn_.

**Comment by mrbaseman** [comment]
in bash strings starting with an exclamation mark refer to the most recent entry in the history, starting with that particular string. The exclamation mark can be escaped by the backslash. Alternatively, you can enclose the string in single quotes (event substitution is also processed in strings enclosed in double quotes).
