### ISSUE TITLE
Feature request, fork in background

### ISSUE THREAD

**Issue by skuti-is** [adrienverge/openfortivpn#229]
Add command line and config file option to fork in background and specify log file.

**Comment by dweggemans** [comment]
Any suggestions on how to do accomplish this with the current version?

**Comment by DimitriPapadopoulos** [comment]
You may start _openfortivpn_ as a _systemd_ service:
* `StandardOutput=` should redirect the output of _openfortivpn_ to a file.
* With `Type=simple`, I think the PID of _openfortivpn_ is known to _systemd_.
* `Restart=` can be used instead of `--persistent`.
* Is forking really required?

As was the case with `--persistent`, I would rather see daemon-like options implemented in _systemd_. Perhaps we could create a wiki to explain how to start _openfortivpn_ as a service. Alternatively, if really needed inside _openfortivpn_, the requested functionality could perhaps be implemented in a _daemonize()_ function that could include the --persistent` functionality.

@skuti-is @dweggemans Can you expand on why it would be better to implement daemon-like functionality in _openfortivpn_ rather than use _systemd_? I am not against the suggestion by the way, just trying to get the big picture.

**Comment by jandersonbt** [comment]
I second the _systemd_ options.  Using existing technologies to accomplish tasks is always best.  I would also like to see the ability to use `Type=notify` in the service file.  Currently, I am working on a project where other services need to start after openfortivpn has the tunnel up and running.  However, when using `Type=simple` in my _systemd_ service file the service shows as complete before the tunnel is up and running. I can see this behavior when using `tail -f` to view the syslog file while restarting the openfortivpn service.  I did attempt to use the `Type=notify` option, however openfortivpn doesn't notify _systemd_ when the tunnel is up and running, and this leaves the systemctl command hanging.  I've been reviewing systemd documentation, but I have yet to find a way around the notify option to accomplish what I need.  Currently, I'm using a `sleep` command to pause while the vpn connects.  This works as long as the vpn connects quickly.

**Comment by DimitriPapadopoulos** [comment]
@jandersonbt Any clue/link how to implement the _systemd_ notification? Additional headers needed and libraries to link with?

**Comment by DimitriPapadopoulos** [comment]
Any clue about _systemd_-like functionality on FreeBSD and macOS?

**Comment by DimitriPapadopoulos** [comment]
@jandersonbt Would it be possible to parse _openfortivpn_ output (in an encapsulating script?) to notify _systemd_, perhaps using [`systemd-notify`](https://www.freedesktop.org/software/systemd/man/systemd-notify.html)?
