### ISSUE TITLE
bug: --no-dns and set-dns=0 not working

### ISSUE THREAD

**Issue by skuti-is** [adrienverge/openfortivpn#230]
/etc/resolv.conf file is updated when starting vpn.
With --no-dns on command line and set-dns=0 in config file.

Ubuntu 16.04.3 xenial
Kernel 4.4.0-96-generic x86_64
INFO:   Got addresses: [10.250.255.1], ns [192.168.170.5, 192.168.1.99]

openfortivpn v1.5.0 3af718e

**Comment by DimitriPapadopoulos** [comment]
It''s probably not _openfortivpn_ modifying this file, see [tunnel.c](https://github.com/adrienverge/openfortivpn/blob/master/src/tunnel.c#L69):
```
	if (tunnel->config->set_dns) {
		log_info("Adding VPN nameservers...\n");
		ipv4_add_nameservers_to_resolv_conf(tunnel);
	}
```
Do you see the "_Adding VPN nameservers..._" message?

Rather it's probably _pppd_ modifying the file, see option `--pppd-no-peerdns` in [main.c](https://github.com/adrienverge/openfortivpn/blob/master/src/main.c#L87).

What happens if you add option `--pppd-no-peerdns`?

Not sure if and why we need two distinct options at this point, and I do understand this can be confusing. I suggest we first focus on understanding what happens, then we can discuss/modify that if needed.

**Comment by jeremyj** [comment]
I agree with you since I do not see "_Adding VPN nameservers..._"  and with `--pppd-no-peerdns` it works.
Thanks

**Comment by DimitriPapadopoulos** [comment]
OK, so we need to:
* understand why DNS is handled in two places (_openfortivpn_ and _pppd_) and why there are two associated options,
* somehow merge these options/features, or not,
* document the relation between `--no-dns` and `--pppd-no-peerdns`.

**Comment by skuti-is** [comment]
updated vpn config file and this works like a charm
set-dns = 0
pppd-use-peerdns = 0

**Comment by DimitriPapadopoulos** [comment]
@adrienverge and @mrbaseman Do you know why `/etc/resolv.conf` can be modified from two different subsystems (_openfortivpn_ itself and _pppd_)?

**Comment by adrienverge** [comment]
Sorry, I have no idea...

**Comment by mrbaseman** [comment]
the `--set-dns` option came from https://github.com/adrienverge/openfortivpn/commit/93e99d77120654fbf4fec94c78c2f36daf51710d#diff-75218e1e64b8201a55c2ac2203e8970c where it replaced the previous `--no-dns` option, whereas `--pppd-no-peerdns` came a bit earlier with commit https://github.com/adrienverge/openfortivpn/commit/a190af9c7a2bbe824bb5d2e8c4cd6b0cbe6d7f43#diff-75218e1e64b8201a55c2ac2203e8970c
The `set-dns` config file option was there first with https://github.com/adrienverge/openfortivpn/commit/a64bc64d93a1adaa1f4d612fbcc94e51e66174c1#diff-75218e1e64b8201a55c2ac2203e8970c but the command line switch called `--no-dns` at that time was there from the very beginning: https://github.com/adrienverge/openfortivpn/commit/171cebae7db0c0dbd5d0609c2d4a52ed98a05182#diff-803c5170888b8642f2a97e5e9423d399 and there has always been the `usepeerdns` option in the pppd command line https://github.com/adrienverge/openfortivpn/commit/171cebae7db0c0dbd5d0609c2d4a52ed98a05182#diff-5df244ea721353ca452473c7213d3f27 (until  `--pppd-no-peerdns` was introduced which was the first control mechanism to tell `pppd` not to manipulate `/etc/resolv.conf`). Maybe in earlier times the built-in mechanism in _openfortivpn_ was a fallback for casese when `pppd` failed to update  `/etc/resolv.conf` but this was before I was involved with  _openfortivpn_.

**Comment by DimitriPapadopoulos** [comment]
As far as I can see the default is:
`set_dns = 1`
`pppd_use_peerdns = 1`
which means both _openfortivpn_ and _pppd_ attempt to modify `/etc/resolv.conf`. Not sure how this makes sense. According to the previous comments, option `--set-dns=0`doesn't have much effect so I suspect we should switch to `set_dns = 0` before planning a complete elimination of this option.

For the next version is suggest we:
* either remove the `--no-dns` option completely, or at least remove it from the documentation,
* remove `--set-dns` from the documentation and change the default to `--set-dns=0` instead of `--set-dns=1`.
Later we can phase out `--set-dns` completely once we're certain it's not needed.

**Comment by skuti-is** [comment]
Just thinking here.
For easy use and understanding of config I would keep set_dns and --set-dns and make it call/trigger the same functions as pppd_use_peerdns.

Note that i have no clue how hard it is to implement.

**Comment by DimitriPapadopoulos** [comment]
If it appears we can/should let _pppd_ modify the DNS resolver configuration, it might be easier to eventually keep a single option. Perhaps `set_dns` is better than `pppd_use_peerdns`: for end-users it is (or should be) irrelevant whether it's _pppd_ or _openfortivpn_ directly handling the the DNS resolver configuration.

The only issue I think of is #101: _add a way to use openresolv_. If this is handled gracefully by recent versions of _pppd_, then we should definitely let _pppd_ handle the DNS resolver configuration. If not, there might be cases where it would be better to disable that in _pppd_ and implement it properly in _openfortivpn_ instead.

Some links found so far:
* [[Buildroot] pppd makefile moves /etc/PPP/resolv.conf](http://lists.busybox.net/pipermail/buildroot/2015-January/118056.html)
* [FS#23198 - [ppp] Add option to use openresolve to manage /etc/resolv.conf](https://bugs.archlinux.org/task/23198)
* [Adding openresolv to base](https://mail-index.netbsd.org/tech-userlevel/2009/03/24/msg001931.html)

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos you mention #101 and I have implemented the `ipparam` feature in reaction to that issue. I think this was the only missing bit, and apart from that the request in #101 was that _openfortivpn_ should *not* touch `resolv.conf` and let _pppd_ or _openresolv_ update it. 
So, #101  is an argument **for** letting _pppd_ modify the DNS resolver configuration rather than against doing so.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I am using _openfortivpn_ with the following configuration and it works flawlessly for me:
```
set-dns = 0
pppd-use-peerdns = 1
```
Would you agree on setting `set-dns = 0` by default? Then if we don't get feedback over time we could even remove the relevant part of the code in the long term.

**Comment by DimitriPapadopoulos** [comment]
@skuti-is skuti-is In upcoming versions of _openfortivpn_ `--set-dns=0` should be sufficient to avoid updating `/etc/resolv.conf I hope this solves this issue the way you suggested. Please tell us if that's not the case.

See f3830844.
