### ISSUE TITLE
Connection error w/ client cert: Could not authenticate to gateway (No cookie given).

### ISSUE THREAD

**Issue by hannesweisbach** [adrienverge/openfortivpn#267]
Hi,

I'm using openfortivpn 1.6.0 on macOS 10.12.6. I'm trying to connect to a VPN gateway with the following command:

```
sudo openfortivpn vpn<redacted>:443 --user-cert=$HOME/Documents/cert.pem -u notused -p notused -vvvv
Password:
WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
WARN:   Bad port in config file: "0".
DEBUG:  Loaded config file "/usr/local/Cellar/openfortivpn/1.6.0/etc/openfortivpn/config".
DEBUG:  Config host = "vpn<redacted>"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "notused"
DEBUG:  Config password = "********"
DEBUG:  server_addr: <redacted>
DEBUG:  server_port: 443
DEBUG:  gateway_addr: <redacted>
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
DEBUG:  server_addr: <redacted>
DEBUG:  server_port: 443
DEBUG:  gateway_addr: <redacted>
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
INFO:   Logged out.
```

The FortiClient application is able to connect to this VPN. I had openfortivpn working a while ago; I'm not sure what I'm doing wrong now. Can someone give any advise?

**Comment by DimitriPapadopoulos** [comment]
Let's see.

> `WARN: Bad port in config file: "0".`

The default configuration file (`/usr/local/Cellar/openfortivpn/1.6.0/etc/openfortivpn/config`?) seems to have been modified. Anyway, this is just a warning and the explicit arguments (should) have precedence over the configuration file.

> ```
> DEBUG: Loaded config file "/usr/local/Cellar/openfortivpn/1.6.0/etc/openfortivpn/config".
> DEBUG:  Config realm = ""
>DEBUG:  Config port = "443"
>DEBUG:  Config username = "notused"
>DEBUG:  Config password = "********"
>DEBUG:  server_addr: <redacted>
>DEBUG:  server_port: 443
>DEBUG:  gateway_addr: <redacted>
>DEBUG:  gateway_port: 443
>DEBUG:  Gateway certificate validation succeeded.
>INFO:   Connected to gateway.````

So far so good.

> ````ERROR:  Could not authenticate to gateway (No cookie given).```

Could it be a subtle typo in  the username/password combination?

Which exact version of _openfortivpn_ is this? The formal release 1.6.0 or the current Git master branch? Also which version of _openfortivpn_ used to work before? If that's not too much hassle for you, could you try that older version again to make sure the error is related to the new version in _openfortivpn_ and not a change in the environment?

Indeed I cannot find substantial recent changes in _get_auth_cookie()_ that could explain this error. The relevant code in [`src/http.c`](https://github.com/adrienverge/openfortivpn/blame/master/src/http.c#L300-L333) looks like this:
```
	ret = ERR_HTTP_NO_COOKIE;

	line = find_header(buf, "Set-Cookie: ");
	if (line) {
		...
		// other debug/error messages
		...
	}
	return ret;
```
and it looks lke `line`  is `NULL`. I cannot find significant changes in  _find_header()_ that would explain that.

**Comment by mrbaseman** [comment]
Proxy support has been added recently. If no proxy is involved (and I don't see any debug output indicating a proxy_host), then `server_addr` and  `gateway_addr` should be the IP address of your vpn gateway (@hannesweisbach can you confirm this?). Since we see that you are connected, I assume that all this works correctly up to this point, but just to be sure we aren't missing something here.

Also, "No cookie given" just means that the vpn did not let you in for some reason. @DimitriPapadopoulos has already mentioned a simple typo as one possible explanation. BTW. you specifically supply a user and you just don't want to show it here or it is literally the username "notused", right? If I'm not mistaken apart from the client certificate you also have to supply the corresponding username.

If you are already logged in via FortiClient and the vpn has a limit configured for the number of connections per account, I think what happens is that all these connections are aborted when you hit the limit. You should then be able to connect if you try once more.

It is also possible to limit vpn accounts to specific ip ranges for very specific use cases. If such a limit is imposed and you come from a different network you also won't receive a cookie.

"Gateway certificate validation succeeded." indicates that the server certificate is accepted by the client, but the client certificate is still valid (just to rule out typical mistakes with certificates)?

**Comment by hannesweisbach** [comment]
Thanks for your replies.

@DimitriPapadopoulos:
I installed openfortivpn via homebrew, which in turn downloads https://github.com/adrienverge/openfortivpn/archive/v1.6.0.tar.gz
As far as I can tell, this has not been updated since the beginning of this year, when I first tried openfortivpn.

@DimitriPapadopoulos @mrbaseman 
I can confirm that server_addr and gateway_addr contain the IP address of the VPN-gateway.
Username/password: I was supplied only with a certificate and the instructions I got along with the certificate explicitly say to leave the username/password empty in the FortiClient configuration. I thought that means the server ignores that and I can pass anything (openfortivpn does not allow empty user names). Do you know what FortiClient passes in those cases? I don't remember what I used beginning of the year but the connection worked using openfortivpn. So yes, I used a literal "notused" ;) Hm, that means I probably have to figure out the username. I don't I'll get a lot of support from the organization I'm connecting to because they want me to use FortiClient. But your answers pushed me in the right direction, I guess.

@mrbaseman 
I'm not using FortiClient and openfortivpn at the same time, I've tried them one after the other, so I guess I'm good on the multiple connections front. I've also tried them from the same network.

> "Gateway certificate validation succeeded." indicates that the server certificate is accepted by the client, but the client certificate is still valid (just to rule out typical mistakes with certificates)?

You mean if my cert is still valid?
```
openssl x509 -enddate -noout -in $HOME/Documents/cert.pem
notAfter=Dec 12 23:47:02 2023 GMT
```

**Comment by hannesweisbach** [comment]
Ah, never mind. I was too stupid to correctly extract key + cert from the p12 :/
On the plus side, it works now :)
