### ISSUE TITLE
Wrong 'default route' added

### ISSUE THREAD

**Issue by josepmc** [adrienverge/openfortivpn#272]
The network config I have is the following (I'm randomizing the IPs):
- eth0 - main gateway, dhcp
- eth1 - has route to the VPN server

My route before connecting looks like this:
0.0.0.0    10.0.0.1 0.0.0.0 ... 100 ... eth0
**vpn address** 192.168.0.1 255.255.255.255 ... 10 ... eth1

Now, when I connect with openfortivpn (latest from master), the following route is added:
**vpn address** 10.0.0.1 255.255.255.255 ... 0 ... eth0

Which actually messes up the entire configuration and blocks any access to vpn-bound addresses until I manually delete the route. Obviously I can just create a small script to workaround this issue, but I actually though on using the persistence option that was added recently.

When killing openfortivpn, the following additional message will be shown:
`WARN:   Could not delete route to vpn server (No such process).`

In any case, wouldn't it be worthwile to add a flag to avoid this behavior?

**Comment by DimitriPapadopoulos** [comment]
There are two ways to handle that:
* Try option `--half-internet-routes=1` (**not** the `--persistent`option which unless I am missing something is totally unrelated) and please report whether it works.
* Use options `--set-routes=0` and handle routes in a script launched when launching/stopping _pppd_.

I guess this is a configuration that hasn't been tested much. Does the _FortiClient_ proprietary client work any better here? What are the routes before/after?

**Comment by josepmc** [comment]
I tried with half-internet-routes to no avail.

A pppd script is also an alternative, but I still believe the behavior is inherently wrong.

On 03 Apr 2018, at 10:50, Dimitri Papadopoulos Orfanos <notifications@github.com<mailto:notifications@github.com>> wrote:


There are two ways to handle that:

  *   Try option --half-internet-routes=1 (not the --persistentoption which unless I am missing something is totally unrelated) and please report whether it works.
  *   Use options --set-routes=0 and handle routes in a script launched when launching/stopping pppd.

I guess this is a configuration that hasn't been tested much. Does the FortiClient proprietary client work any better here? What are the routes before/after?

**Comment by DimitriPapadopoulos** [comment]
Indeed the behaviour is probably wrong. Personally I cannot test that because I don't have a machine attached to two networks. Tight now:
* It would help to know how the proprietary _FortClient_ handles such a setup (routes before/after).
* I have no clue how easily this can be fixed because I don't have a good understanding of the problem.

**Comment by mrbaseman** [comment]
I understand the problem. It's the mechanism in [ipv4_protect_tunnel_route](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L466). The idea behind this is if the vpn gateway pushes a route which contains the vpn gateway itself a route through the tunnel interface is added which breaks the transport of the ssl encrypted data stream. The assumption behind this is that the vpn gateway usually is covered by the default route, because it is somewhere outside on the internet and you want to connect to it from varying places... So good so far. Maybe it already helps if we properly determine which routing entry is the one that is used to access the gateway before the connection is established, but I need a closer look.

**Comment by mrbaseman** [comment]
On linux one could parse the output of `ip route get <gtw_rt>` and on MacOSX it is `route get <gtw_rt>` (no ip command there). 
Probably with the `netlink` kernel API it's possible doing it in C. 
a couple of (perhaps) useful links:
* http://kernelspec.blogspot.de/2014/10/zoom-into-packet-routing-in-linux-kernel.html
* https://www.linuxquestions.org/questions/linux-networking-3/howto-find-gateway-address-through-code-397078/
* https://stackoverflow.com/questions/25348409/using-rtnetlink-reply-message-type-to-rtm-getroute-message

**Comment by mrbaseman** [comment]
I just noticed that `netlink` is not available on MacOS X. So, if we want portable code, [ioctl](https://en.wikipedia.org/wiki/Ioctl) might be the choice, even though the request codes differ between the various supported platforms...

**Comment by mrbaseman** [comment]
ah, I just see that we already have a [ipv4_get_route](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L113) which just might need some small modifications, in order to better match the routes to specific destinations. Currently, it looks for the routing entry in which both, the address and the netmask match. That's probably what we want when manipulating the routing table, but the routing algorithm checks all routes and uses the one that matches and has the smallest netmask. I'll work on a solution. 
Sorry for the confusion that my previous two comments might have caused. I'll delete them.

**Comment by mrbaseman** [comment]
@josepmc can you try my [improve_getroute Branch](https://github.com/mrbaseman/openfortivpn/tree/improve_getroute). I have tried to build a similar environment, at least with my workstation being dual homed and the vpn gateway behind the interface which does not have the default route. It seems to work here, but I can reach the vpn on both paths, so it's probably not exactly the same situation as in your case.

**Comment by mrbaseman** [comment]
I have just landed a fix for this issue on master. 
@adrienverge what do you think about a new release? We have landed a bunch of improvements on master in the meantime.

**Comment by adrienverge** [comment]
@mrbaseman, sure! Version 1.7.0 released!

**Comment by DimitriPapadopoulos** [comment]
@josepmc Does version 1.7.0 help?

**Comment by josepmc** [comment]
Yes, this issue is solved now :).

Thanks!

On 20 May 2018, at 09:43, Dimitri Papadopoulos Orfanos <notifications@github.com<mailto:notifications@github.com>> wrote:


@josepmc<https://github.com/josepmc> Does version 1.7.0 help?

**Comment by DimitriPapadopoulos** [comment]
Fixed by #285.
