### ISSUE TITLE
No contextual menu for sytem-tray icon in Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by stremblay** [adrienverge/openfortivpn#302]
Hello, I have just installed Ubuntu Mate v18.04 in a Virtualbox VM. It looks like the contextual menu for the system tray icon is not displaying or shows up empty when I click on the icon. I used Mate tweak to modify my desktop a bit and basically changed my panel layout as "Redmond". That's about the only change I made other than installing a different theme in the Appearance Preferences.

Also, if I close the main window I am left with only the icon in the system tray. If I double-click, the main window does not come back. And I have no other way to make the main window reappear. I am then forced to kill the app on the command line, but then the process becomes defunct.

Let me know if there is anything else I can do to provide you with more info.

I have attached a screenshot to show you what it looks like.

![capture](https://user-images.githubusercontent.com/413282/39898319-33defef4-5484-11e8-9eb0-5a88c0204fba.JPG)

**Comment by tadeboro** [comment]
I am afraid that this has nothing to do with the openfortivpn, since this is a command-line program with no GUI elements.

You are probably experiencing issues with NetworkManager integration into Mate desktop. Running this on Ubuntu does not help either, since NetworkManager VPN plugin for Fortinet is [slightly broken](https://bugs.launchpad.net/ubuntu/+source/network-manager-fortisslvpn/+bug/1770392). You should probably bring this issue up with Mate/Ubuntu devs.
