### ISSUE TITLE
X509_check_host detection always fails

### ISSUE THREAD

**Issue by tadeboro** [adrienverge/openfortivpn#304]
Configuration process fails to detect X509_check_host function even on systems that have it defined.

## Steps to reproduce

 1. Ensure we have proper verison of OpenSSL using `pkg-config --modversion libssl` (should return `1.1.0` or `1.0.2`).
 2. Clone the repository.
 3. Run `./autogen.sh`.
 4. Run `./configure.sh`.
 5. One of the last lines in the output is `checking for X509_check_host... no`.

This was tested on Fedora 27 (OpenSSL 1.1.0h) and unstable Gentoo (OpenSSL 1.0.2o).

## What is causing the issue

Main reason for this issue is the fact that PKG_CHECK_MODULES does not add proper linker flags to the set of flags that configure is using to check for function presence. This can be seen in the config.log file:

    configure:5102: checking for X509_check_host
    configure:5102: gcc -o conftest -g -O2   conftest.c -lutil -lpthread  >&5
    /tmp/cckiBJJz.o: In function `main':
    /home/tadej/devel/openfortivpn/conftest.c:184: undefined reference to `X509_check_host'
    collect2: error: ld returned 1 exit status

In the second line, `-lssl` and `-lcrypto` linker flags are missing.

## How to fix this

Initial stab at fixing this issue in in pull request #303

**Comment by DimitriPapadopoulos** [comment]
I've merged your pull request as it doesn't seem to be breaking anything.

But why "initial stab"? Is there anything else we might need to change?

**Comment by DimitriPapadopoulos** [comment]
Excellent then.

It just occurred to me that we may need to check a couple things:

1. How does this behave on macOS? @mnencia Does it still build on macOS or do you need to change the _homebrew_ recipe?
2. Is _pkg-config_ still useful? @mrbaseman Should we modify `configure.ac` by removing the relevant lines since this should be entirely handled by _autoconf_ internally? ```m4_ifndef([PKG_PROG_PKG_CONFIG], [m4_fatal([Please install pkg-config.])])
PKG_PROG_PKG_CONFIG```

**Comment by DimitriPapadopoulos** [comment]
It looks like _autotools_ are a little bit broken/inconsistent here:
* _PKG_CHECK_MODULES_() does set/report a few variables:
```
pkg_cv_OPENSSL_CFLAGS=
pkg_cv_OPENSSL_LIBS='-lcrypto -lssl'
```
```
OPENSSL_CFLAGS=''
OPENSSL_LIBS='-lcrypto -lssl'
```
* _AC_CHECK_FUNCS_() does not use them:
```
configure:5114: gcc -o conftest -g -O2   conftest.c -lutil -lpthread  >&5
/tmp/cc4iZwHK.o: In function `main':
/volatile/src/openfortivpn/conftest.c:184: undefined reference to `X509_check_host'
collect2: error: ld returned 1 exit status
```

**Comment by DimitriPapadopoulos** [comment]
I see two solutions:
* use _AC_CHECK_LIB()_ **in addition** to _PKG_CHECK_MODULES()_,
* get _AC_CHECK_FUNCS()_ to honour variables from _PKG_CHECK_MODULES()_, probably by passing explicitly a few arguments to _AC_CHECK_FUNCS()_.

**Comment by DimitriPapadopoulos** [comment]
The problem with solution 1 is that:
* _AC_CHECK_FUNCS()_ does **not** use the header and library search paths provided by _pkg-config_,
* the _openfortivpn_ build instructions **do** take in to account the header and library search paths provided by _pkg-config_.

So these two different build steps may test / build against different headers/libraries!

Either we take the solution of @tadeboro and abandon -pkg-config_, or we find a way to reconcile _PKG_CHECK_MODULES()_ and _AC_CHECK_FUNCS()_.

**Comment by DimitriPapadopoulos** [comment]
Some reading:
* [PKG_CHECK_MODULES considered harmful?](https://stackoverflow.com/questions/10220946/pkg-check-modules-considered-harmful)

**Comment by DimitriPapadopoulos** [comment]
Back to solution 1.

It looks like adding:
```
CPPFLAGS="${CPPFLAGS} ${OPENSSL_CFLAGS}"
LIBS="${LIBS} ${OPENSSL_LIBS}"
```
right after
```
PKG_CHECK_MODULES(OPENSSL, [libcrypto libssl])
```
enforces the relevant header and library search paths are taken into account both when running _AC_CHECK_FUNCS()_ and during actual compilation.

**Comment by DimitriPapadopoulos** [comment]
By the way, I'm putting `OPENSSL_CLFAGS` in to _ CPPFLAGS_ because of [this remark on PKG_CHECK_MODULES](https://autotools.io/pkgconfig/pkg_check_modules.html#idm45453220059312):
> By default, the macro will set up two variables, joining the given prefix with the suffixes _CFLAGS and _LIBS. The names of these variables can be somewhat misleading, since the former will generally provide the flags to pass to the preprocessor, rather than the compiler, such as include paths and macro definitions, and the latter will provide the library paths as well as the libraries themselves.

**Comment by tadeboro** [comment]
What about if this package would simply require OpenSSL >= 1.0.2? This version of OpenSSL was released in January 2015 and is present in most currently supported distributions and OSX. I checked:

 1. Ubuntu has this from Trusty (released in April 2014).
 2. Debian has this from Jessie (released in April 2015).
 3. Fedora has this form 23 (released in November 2015).
 4. Gentoo has this in stable tree.
 5. Homebrew for OSX has latest stable (1.0.2o) already packaged.

This way, we can simply set the minimum version directly in the PKG_CHECK_MODULES, get rid of the `x509_check_host` function check and remove the string comparison check in `tunnel.c` file.

Any thought about this?

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman has recently changed the whole _autotools_ machinery to check for each required function and fail if any required function is missing - or define `HAVE_FUNCTION` if an optional function is available.
We cannot avoid checking _X509_check_host()_ in _AC_CHECK_FUNCS()_, either as an optional or as required function.

**Comment by tadeboro** [comment]
Current autotools machinery in openfortivpn only performs checks for functions that reside in either standard library or in one of the libraries that we find using AC_CHECK_LIB macro. None of the OpenSSL functions are being checked for, with the exception of X509_check_host which this is meant to be an optional dependency. If OpenSSL functions were checked for using AC_CHECK_FUNCS, the configure would fail because some linker flags would be missing (just like described in initial bug report).

If we require OpenSSL to be of version 1.0.2 or higher, we can rely on X509_check_host being available just like we already do with other OpenSSL functions. This would make it possible to remove the preprocessor if in [tunnel.c](https://github.com/adrienverge/openfortivpn/blob/master/src/tunnel.c#L555) and always use x509_check_host. And since HAVE_X509_CHECK_HOST define is only used in this particular place, we can also remove the offending AC_CHECK_FUNCS call, resolving our troubles.

But as said before, this can only be done if maintainers are happy to leave some really old systems not being able to use latest openfortivpn.

**Comment by DimitriPapadopoulos** [comment]
True. Then perhaps your solution is the proper one - check for a recent version of OpenSSL and fail if it's not found. Yes, I agree with you: let's just require a minimal version of OpenSSL and get rid of `AC_CHECK_FUNCS([X509_check_host])`.

Here is an alternative based on solution 2 and inspired by code seen in other software after a web search:
DimitriPapadopoulos/openfortivpn@e3f1d69

**Comment by DimitriPapadopoulos** [comment]
I vote for the pull request #306 suggested by @tadeboro.

The alternative would be to fix the current solution as in pull request #307, where we take into account compiler/linker flags provided by PKG_CHECK_MODULES not only in `Makefile.am` but also when calling AC_CHECK_FUNCS in `configure.ac`.

**Comment by DimitriPapadopoulos** [comment]
Ouch! The Travis CI platform obviously uses an older version of OpenSSL, so we cannot pass the test!

How do we get the Travis CI platform to use a more recent platform?

**Comment by DimitriPapadopoulos** [comment]
`trusty` is not sufficient:
https://packages.ubuntu.com/source/trusty/openssl

We need `xenial`:
https://packages.ubuntu.com/source/xenial/openssl

**Comment by DimitriPapadopoulos** [comment]
Besides this doesn't work either:
`dist: xenial`

Strange. This needs more debugging but I don't have much experience with Travis CI and don't know how to debug.

**Comment by tadeboro** [comment]
I reworked Travis integration a bit and made sure that we test the compilation against specific version of the OpenSSL package. Those changes should make it possible to resolve issues in pull request #306

**Comment by DimitriPapadopoulos** [comment]
Ah `xenial` and `bionic` are indeed not [available on Travis CI](https://github.com/travis-ci/travis-ci/issues/5821). Let's have a look at #308.

**Comment by tadeboro** [comment]
Is there anything else needed in order to resolve this issue one way or another?

**Comment by DimitriPapadopoulos** [comment]
Not at all. I'd just like some more feedback. As far as I'm concerned, I vote for #306, like you.

**Comment by mrbaseman** [comment]
* I would vote for #307 because older, but still supported enterprise distros (RHEL/CentOS 6, SLES 11sp4) ship with (heavily patched) older versions of _openssl_

* There was also the [question](https://github.com/adrienverge/openfortivpn/issues/304#issuecomment-388377703) if `pkg-config` is still useful. I think it is a good way to specify the location of some dependencies, e.g. within `homebrew`. 
First we had a configure option in #144 and switched to `pkg-config` in #151. Obviously, there were some bits missing for the transition to `pkg-config`, but all in all I believe it is better than maintaining our own configure switches for _openssl_. 

* `X509_check_host` currently is the only _openssl_ function that is explicitly checked, because we have to determine if it exists. All other functions should always be there (assuming that nobody uses an ssl library below 0.9.8 nowadays...). The assumption is that `autoconf` and `pkg-config` would find the library and do some basic tests like if compiling and linking works.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Let's go for #307 then. Indeed it can be useful to be able to ship a recent version of _openfortivpn_ on older distributions that have not yet reached EOL (CentOS 6 in 2020 and SLESS 11 SP4 in 2022).

Perhaps I'll change:
```
PKG_CHECK_MODULES(OPENSSL, [libcrypto libssl])
```
into:
```
PKG_CHECK_MODULES(OPENSSL, [libcrypto >= 0.9.8 libssl >= 0.9.8])
```
to explicitly state that we expect OpenSSL >= 0.9.8.

**Comment by DimitriPapadopoulos** [comment]
Forget my comment about `pkg-config` - I don't understand it either! Perhaps I had misread some documentation. I really don't know.

**Comment by DimitriPapadopoulos** [comment]
Found the documentation that states that `PKG_CHECK_MODULES` implicitly calls `PKG_PROG_PKG_CONFIG` first:
* [3. The PKG_CHECK_MODULES Macro](https://autotools.io/pkgconfig/pkg_check_modules.html)
* [add PKG_PROG_PKG_CONFIG to configure.ac](https://github.com/varnish/varnish-nagios/issues/1)

Adding these lines:
```
m4_ifndef([PKG_PROG_PKG_CONFIG], [m4_fatal([Please install pkg-config.])])
PKG_PROG_PKG_CONFIG
```
may result in a cleaner error message (`Please install pkg-config.`) - but is it worth the pain?

**Comment by DimitriPapadopoulos** [comment]
See [`pkg.m4`](https://cgit.freedesktop.org/pkg-config/tree/pkg.m4.in#n93).

**Comment by mrbaseman** [comment]
I think we need `PKG_PROG_PKG_CONFIG` in order to be able to use `PKG_CHECK_MODULES`, otherwise `pkg-config` might not be found even if it is installed, and therefore information from the .pc files would not be considered. So, if we support `pkg-config` we should keep `PKG_PROG_PKG_CONFIG` and the [m4_ifndef-line](https://github.com/adrienverge/openfortivpn/blob/master/configure.ac#L12) makes the error message more understandable when `pkg-config` is not installed.

So, your question "is it worth the pain" targets the whole `pkg-config` interface, including  `PKG_CHECK_MODULES`, right? 

The alternative would be going back to something along the lines of #144 but compared to that #307 looks much more elegant.

**Comment by DimitriPapadopoulos** [comment]
As far as I can see `PKG_CHECK_MODULES` starts by calling call `PKG_PROG_PKG_CONFIG`. See [this line of `pkg.m4`](https://cgit.freedesktop.org/pkg-config/tree/pkg.m4.in#n93).

I meant to say that you don't need to call `PKG_PROG_PKG_CONFIG` explicitly, since  you call `PKG_CHECK_MODULES` which in turn calls `PKG_PROG_PKG_CONFIG`.

I agree though that the [m4_ifndef-line](https://github.com/adrienverge/openfortivpn/blob/master/configure.ac#L12) makes the error message more understandable when `pkg-config` is not installed. My question "is it worth the pain" targets this specific line only, **not** `PKG_CHECK_MODULES`.

**Comment by mrbaseman** [comment]
Ah, now I got your point. hmm... 

...but then the "pain" is not very big :-) 

it's one line which is redundant (at least in current versions of `pkg-config` (not sure if [this line of pkg.m4](https://cgit.freedesktop.org/pkg-config/tree/pkg.m4.in#n93) has always been there), and one line which helps finding the problem when `pkg-config` is not installed.
