### ISSUE TITLE
url_encode() doesn't work for utf-8

### ISSUE THREAD

**Issue by darddan** [adrienverge/openfortivpn#401]
in `src/http.c` in function `url_encode` the `isalnum()` works with ASCII characters only. So if a username contains special characters from other languages that aren't in ASCII then it can't authenticate them.

**Comment by DimitriPapadopoulos** [comment]
Thinking about it again, are you certain the point of failure is here? `isalnum()` is used precisely to distinguish ASCII characters (which don't need further encoding) and non-ASCII characters which **are** handled as far as I can see [later on](https://github.com/adrienverge/openfortivpn/blob/01898c3/src/http.c#L49-L55).

Have you experienced actual failures? If so are you certain the problem is in this part of the code or even in _openfortivpn_?

**Comment by darddan** [comment]
Yes I have experienced this problem today. I was trying to use [ł](https://en.wikipedia.org/wiki/%C5%81) on the username and it wasn't working. 
I did [this](https://github.com/darddan/openfortivpn/commit/f05ffdee4eaebecb7fd13954d14e4c70416beea2) as a workaround and now it works. I tried to implement it in a better way but it appears that checking if an utf-8 character in c is a little more complicated than I thought.

**Comment by darddan** [comment]
Found the issue, fixed it and explained it in the pull request comment.
I tested it by adding: 
```
	printf("%s\n", username);
	exit(0);
```

after 

```
	url_encode(username, tunnel->config->username);
```

in lines `535` and `536`

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I think we get UTF-8 encoded strings from all sources:
* I expect configuration files to be UTF-8 encoded.
* I believe the arguments passed to `main()` are also UTF-8 encoded under most locales on Linux/macOS/BSD.
* Also I believe _getchar_() and other functions we use for user input return UTF-8 encoded strings as well.

On my own Linux computer, the following test program:
```C
#include <stdio.h>

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; i++) {
        printf("argv[%d]:", i);
        for (unsigned char *c = (unsigned char *)argv[i]; *c; c++)
            printf(" 0x%2x", *c);
        printf("\n");
    }

    printf("Enter a character: ");
    int c = getchar();
    while (c != EOF && c != '\n') {
        printf("0x%2x ", c);
        c = getchar();
    }
    printf("\n");
}
```
shows UTF-8 encoded strings:
```
$ ./test 1 ł
argv[1]: 0x31
argv[2]: 0xc5 0x82
Enter a character: ł
0xc5 0x82 
$ 
```

Now in the case of @darddan I'm not 100% certain what the encoding is. @darddan are you under an UTF-8 locale on Linux? What is the output of `echo $LANG` on your command line? The `Ł` character is coded as a single byte `0xA3` in ISO 8859-2 or ISO 8859-16, and as two bytes `0xC5` `0x82` in UTF-8.

Now if strings are UTF-8 encoded, I think there are _no_ Unicode code points encoded with a zero byte, except of course code point 0. If so, we can still assume strings are `\0` terminated when we manipulate UTF-8 encoded strings. What **does** changes in UTF-8 is that a character may span multiple bytes instead of a single byte - and it looks like `url_encode()` does not handle that properly today.

**Comment by DimitriPapadopoulos** [comment]
One more reason to switch to a 3rd party compact HTTP library.
