### ISSUE TITLE
Stuck at ssl_read_thread / if_config thread, then terminates with "Error reading from SSL connection"

### ISSUE THREAD

**Issue by falloutghost** [adrienverge/openfortivpn#422]
Hi,

I'm trying to connect to a VPN using the following command:

`sudo openfortivpn xx.xxx.xxx.xx:xxxx -u <username> --trusted-cert <hash> -vvv`

This works on all machines in our office except for mine, which gets stuck with the following output:

```
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "xx.xxx.xxx.xx"
DEBUG:  Config realm = ""
DEBUG:  Config port = "xxxx"
DEBUG:  Config username = "username"
DEBUG:  Config password = "********"
DEBUG:  server_addr: xx.xxx.xxx.xx
DEBUG:  server_port: xxxx
DEBUG:  gateway_addr: xx.xxx.xxx.xx
DEBUG:  gateway_port: xxxx
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=GTGrYFOMkB6o99Ymhu54cARyg/...
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=GTGrYFOMkB6o99Ymhu54cARyg/...
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: xx.xxx.xxx.xx
DEBUG:  server_port: xxxx
DEBUG:  gateway_addr: xx.xxx.xxx.xx
DEBUG:  gateway_port: xxxx
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  pppd_read_thread
DEBUG:  if_config thread
DEBUG:  ssl_write_thread
DEBUG:  ssl_read_thread
```

Sometimes the last output is  `DEBUG: if_config thread` instead of `DEBUG: ssl_read_thread`, seems to be random.

After ~30 seconds, openfortivpn terminates with:

```
DEBUG:  Error reading from SSL connection (Protocol violation with EOF).
INFO:   Cancelling threads...
DEBUG:  Waiting for pppd to exit...
DEBUG:  waitpid: pppd exit status code 16
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: xx.xxx.xxx.xx
DEBUG:  server_port: xxxx
DEBUG:  gateway_addr: xx.xxx.xxx.xx
DEBUG:  gateway_port: xxxx
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.
```

I'm unsure how to debug this, all other machines are using the exact same command, all are running Debian 9.6 and pppd version 2.4.7. I tried openfortivpn versions 1.6.0, 1.8.0 and 1.8.1.

Any ideas or hints where I could be looking to gather more information why this isn't working on my machine?

**Comment by DimitriPapadopoulos** [comment]
While this is probably not related to _pppd_, you can define a log file for _pppd_ using `--pppd-log` as described in the [Wiki](https://github.com/adrienverge/openfortivpn/wiki).

**Comment by falloutghost** [comment]
Sorry, was just about to update the issue with the pppd log:

```
Jan  4 16:45:24 Falcon pppd[17840]: pppd 2.4.7 started by falcon, uid 0
Jan  4 16:45:24 Falcon NetworkManager[433]: <info>  [1546616724.0400] manager: (ppp0): new Generic device (/org/freedesktop/NetworkManager/Devices/31)
Jan  4 16:45:24 Falcon pppd[17840]: Using interface ppp0
Jan  4 16:45:24 Falcon pppd[17840]: Connect: ppp0 <--> /dev/pts/2
Jan  4 16:45:24 Falcon NetworkManager[433]: <info>  [1546616724.0459] devices added (path: /sys/devices/virtual/net/ppp0, iface: ppp0)
Jan  4 16:45:24 Falcon NetworkManager[433]: <info>  [1546616724.0459] device added (path: /sys/devices/virtual/net/ppp0, iface: ppp0): no ifupdown configuration found.
```

After `DEBUG:  Error reading from SSL connection (Protocol violation with EOF).`:
```
Jan  4 16:50:25 Falcon pppd[17840]: Hangup (SIGHUP)
Jan  4 16:50:25 Falcon pppd[17840]: Modem hangup
Jan  4 16:50:25 Falcon pppd[17840]: Connection terminated.
Jan  4 16:50:25 Falcon gnome-shell[1517]: JS LOG: Removing a network device that was not added
Jan  4 16:50:25 Falcon NetworkManager[433]: <info>  [1546617025.8945] devices removed (path: /sys/devices/virtual/net/ppp0, iface: ppp0)
Jan  4 16:50:25 Falcon gnome-shell[3421]: JS LOG: Removing a network device that was not added
Jan  4 16:50:25 Falcon pppd[17840]: Exit.
```

**Comment by DimitriPapadopoulos** [comment]
I understand _pppd_ receives a `SIGHUP` signal.

Strange, the `SIGHUP` signal is usually emitted when the controlling terminal is closed. Can you think of anything different in the configuration of your Debian workstation?

**Comment by falloutghost** [comment]
I worked on another project a while ago where I needed to connect to a test instance behind an ipsec/l2tp VPN where I played around with `openswan` and `xl2tpd`, but I purged those and removed all configs I made.

Other than that, I can't really think of anything that might be related. I also don't have any manual `iptables` rules.

**Comment by DimitriPapadopoulos** [comment]
Perhaps the `_pppd_` error message is misleading. Have you tried with the identifiers of one of you colleagues on your own workstation - or the reverse - to make sure this really is related to this workstation and not to your identifiers?

**Comment by falloutghost** [comment]
With identifiers you mean credentials? Then yes, we all use the same user/password.

**Comment by DimitriPapadopoulos** [comment]
I really don't know much (if anything) about FortiGate internals, but could it be that the IP address of your workstation is not white-listed, unlike the IP address of other workstations, or something similar?

**Comment by falloutghost** [comment]
It's the same IP for all machines to the outside :/

**Comment by DimitriPapadopoulos** [comment]
Clearly the _pppd_ `SIGHUP` message does not mean what I thought it means. I have found other [`SIGHUP`-related issues](https://github.com/adrienverge/openfortivpn/issues?q=is%3Aissue+SIGHUP). See [issue #92](https://github.com/adrienverge/openfortivpn/issues/92#issuecomment-318381947) for example. It could be that _openfortivpn_/_pppd_ also die because of a time-out, and the time-out could be related to the VPN not working properly. If so we need to investigate why _openfortivpn_ "stucks" and leave `SIGHUP` aside as it is a mere consequence of a prior problem.

**Comment by mrbaseman** [comment]
My impression so far was that slow connections could cause some kind of timeout, although I'm not sure which ones exactly, nor I have any hard evidences for this hypothesis

**Comment by DimitriPapadopoulos** [comment]
@falloutghost I suppose you don't have access to the log of the Fortigate device, do you? Have you had a look at the system logs (probably `/var/log/syslog`)? In any case, if credentials and IP address are identical between workstations, your own workstation has to be different somehow (environment variables, software updates, or system networking setup).

I suggest you use 1.8.1 instead of 1.6.0 - and certainly not 1.8.0. In version 1.8.1, the error message should be:
```
DEBUG:  ssl_read thread
```
and not:
```
DEBUG:  ssl_read_thread
```

Finally, if you're willing to investigate, this error message:
```
DEBUG: Error reading from SSL connection
```
can be emitted from three different places, always after calling _safe_ssl_read_() or _safe_ssl_read_all_():
[**`src/io.c`**, line 434](https://github.com/adrienverge/openfortivpn/blob/967d481/src/io.c#L434)
[**`src/io.c`**, line 459](https://github.com/adrienverge/openfortivpn/blob/967d481/src/io.c#L459)
[**`src/http.c`**, line 201](https://github.com/adrienverge/openfortivpn/blob/967d481/src/http.c#L201)
You could add some debugging code to find where _openfortivpn_ fails exactly, then add some debugging code to _safe_ssl_read_() or _safe_ssl_read_all_() in **`src/ssl.h`**.

**Comment by falloutghost** [comment]
Thanks for the suggestions, I'll see what I can find.

Quick update, it most definitely has something to do with my OS configuration/environment, since I can connect to the VPN from a docker container from my machine just fine.

**Comment by falloutghost** [comment]
Got it fixed by reinstalling `pppd`:

```
sudo apt-get purge ppp
sudo apt-get install ppp
```

@DimitriPapadopoulos Thanks for your fast reply and your effort :)

**Comment by DimitriPapadopoulos** [comment]
Thank you for investigating and reporting back. It looks like _pppd_ settings were responsible for this. Not sure how to detect this issue since it seems to be caused by _pppd_ failing without an intelligible error message.

It would have been nice to know which _pppd_ setting or script was responsible for this issue. Probably too late for that though.
