### ISSUE TITLE
Build fails on OpenBSD

### ISSUE THREAD

**Issue by vext01** [adrienverge/openfortivpn#430]
Hi,

I need to connect to a fortinet vpn from OpenBSD.

```
$ gmake
...
  CC       src/openfortivpn-http.o
In file included from src/tunnel.h:34,
                 from src/http.h:21,
                 from src/http.c:18:
src/ipv4.h:44: error: redefinition of 'struct rtentry'
src/ipv4.h:51: error: expected ':', ',', ';', '}' or '__attribute__' before '.' token
gmake: *** [Makefile:529: src/openfortivpn-http.o] Error 1
```

The problem is, OpenBSD has an always visible definition of `rtentry`, which, like FreeBSD doesn't have a `rt_dst` member, so you can't redefine your own :\

I'm not sure if there's an easy fix...

**Comment by mrbaseman** [comment]
unfortunately, there isn't an easy fix. autoconf can detect that there is an rtentry structure available, but it doesn't work together with the rest of the code. I have tried to port _openfortivpn_ to OpenBSD first, but the routing structure is substantially different from the one in used in linux (and in the _openfortivpn_ source code). 
OpenBSD uses a radix tree, a pointer to rt_gateway instead of a member in the struct, a reference rt_gwroute to the routing entry for the gateway route whereas it does not have rt_dest and rt_genmask for instance. 
I have tried to write a few macros to transform the rtentry accesses such that it matches the OpenBSD style... but at least I didn't succeed in that task :-(

**Comment by vext01** [comment]
Thanks for the quick reply.

That's a shame.

I don't suppose you know any other way I can connect OpenBSD to a fortinet vpn? I'm not sure if openconnect should work or not...

**Comment by DimitriPapadopoulos** [comment]
Never tried myself, but perhaps you could try IPSec. I think a colleague of mine managed to connect using IPSec from Linux, but as far as I can see it very much depends on the Fortinet appliance settings - and probably depends on the OS too.

**Comment by mrbaseman** [comment]
IP Sec is a completely separate connection. If the administrator of the Fortigate configures it in addition to the SSL VPN that would probably be the easiest option. Apart from the more well-known site2site ipsec, also an ipsec dialup configuration is supported. If I remember right, there is even a wizard for that. I'm using ipsec on Android, too (in addition to my sslvpn).

**Comment by vext01** [comment]
I'm currently waiting on our IT dept to tell us what they support. Maybe I will get lucky...

**Comment by mrbaseman** [comment]
maybe the [Cookbook](https://cookbook.fortinet.com/ipsec-vpn-forticlient/) is helpful here

**Comment by DimitriPapadopoulos** [comment]
@vext01 Have you managed to connect from OpenBSD?

**Comment by vext01** [comment]
Hi,

Sorry, no. I gave up in the end.

**Comment by DimitriPapadopoulos** [comment]
Yes, looks rather complex so I suggest we close this issue for now. Please feel free to reopen if needed.
