### ISSUE TITLE
openfortivpn (through openfortigui) and Firmware 6.x

### ISSUE THREAD

**Issue by TheRealAgentK** [adrienverge/openfortivpn#460]
Hi all! 

thx for openfortivpn and (an extended thx :) for openfortigui.

I'm currently using the tools to connect to a 70D appliance with firmware 5.6.9 currently from Ubuntu Budgie 18.04 and that works great.

Now on my client's side they need/want to upgrade the firmware to 6.0.3 (and 6.0.6 eventually).

The purpose of the setup is basically solely to create a SSLVPN connection into their network using 2FA with an OTP through the FortiToken mobile app, none of the other (commercial) Forticlient features are being used.

I'm wondering if anyone has had any experience with using openfortivpn against firmware 6.x or any opinion on the chances of success? It seems to me that them doing this upgrade bears a higher risk of stuff breaking on my end than the minor upgrades they've gone through previously. 

Currently using openfortigui 0.7.2.2 (which seems to be using openfortivpn at changeset https://github.com/adrienverge/openfortivpn/commits/2aca3891969a8bf9332821e8c997d71c24d8c0a3, looks like somewhere between 1.7.1 and 1.8)

Any feedback very appreciated!

**Comment by mrbaseman** [comment]
Hi,

I'm using openfortivpn to connect to a 60D, currently running 6.0.6, and I'm using the FortiToken mobile app ass second factor. I'm using the 6.0 firmware since 6.0.2 I think. 

With openfortivpn I wouldn't expect any problems with the firmware upgrade on the remote side. We've had a couple of minor issues which we have fixed in the recent versions, but I'm not aware of anything which was particularly related to a remote version of 6.x.

For the communication with openfortigui we have added the config file option for the  one time password (otp) and there was also a change to use this value for 2fa even if that seems to be something slightly different from otp. The config file is dynamically created by the gui somewhere in a ramdisk or so. 

The changes that are related to 2fa, might be a reason for you to upgrade openfortivpn to a more recent version, but I don't see how 2fa is related to the firmware upgrade on the remote side. I have been using the FortiToken App since FortiOS 5.2. The Versions offered in the AppStore and Google Play usually are the ones for the most recent FortiOS, but usually they used to work with all remote versions, at least the FortiToken App which is something different than the FortiClient App (which, among other features, allows to open a VPN tunnel on the mobile device)

**Comment by TheRealAgentK** [comment]
Thx @mrbaseman - that's really valuable feedback and increasing confidence a lot. We'll do the upgrade on their end next week, I'll update this thread with the outcome.

**Comment by TheRealAgentK** [comment]
Quick follow-up - client upgraded to firmware 6.0.2 and then 6.0.5 and my current version of the openfortigui (and openfortivpn) just continued to work without any flaws, including 2FA via the Android/iOS token apps.

Thx, everyone!

**Comment by mrbaseman** [comment]
@TheRealAgentK - thanks for this positive feedback
