### ISSUE TITLE
Add an option to trust certificate

### ISSUE THREAD

**Issue by woprandi** [adrienverge/openfortivpn#468]
Does it possible to have an option to trust interactively or automatically a certificate ? It's annoying to have to grep logs to find the sha256 certificate used and modify the configuration file.

**Comment by DimitriPapadopoulos** [comment]
It looks like the certification authority (CA)  of the FortiGate appliance certificate is unknown to your computer's system (specifically _OpenSSL_). The whole point of certificates is that they are verified against trusted CAs. If the CA associated to the FortiGate appliance certificate is not trusted by the system, perhaps your computer has not been set up according to the expectations of the administrators of the FortiGate appliance. In that case you have to tell _openfortivpn_ to trust the certificate of the FortiGate explicitly. However you only need to do that once in the configuration file.

**Comment by DimitriPapadopoulos** [comment]
@woprandi Does this answer your question - although it might not be the answer you want? Can we close this issue? Please feel free to discuss this issue.

**Comment by DimitriPapadopoulos** [comment]
It might be more helpful to have an option (or even a separate script) to grep the logs and modify the configuration file.

**Comment by woprandi** [comment]
Sorry, I'm not an expert but I will give you my opinion :
If you are an end-user without any technical knowledge and use this plugin
thought the Gnome plugin it's a blocking issue and you won't be able to
connect without help (for the first time and each time the certificate
changes). That's a problem.

**Comment by DimitriPapadopoulos** [comment]
But then why use certificates in the first place?

**Comment by mrbaseman** [comment]
I'd say the best solution to this problem is to get a server certificate from a CA that is commonly trusted by the operating system. The admin can export a signing request from the Fortigate and import the enrolled certificate. 
I think it's also possible to create the CSR and private key externally, pack it together with the certificate and import both into the Fortigate. If not using a  commonly trusted CA but an own one run in the company, the CA certfificate should be properly installed on the client systems (not only because _openfortivpn_ complains, but also other pieces of software that have to deal with encrypted connections).

**Comment by woprandi** [comment]
> But then why use certificates in the first place? This really is a security issue. While I agree this might be a problem for some users, it doesn't mean I have to agree with the proposed solution.
> 
> For end-users who use _openfortivpn_ through the Gnome plugin, I suggest you file an issue directly with [GNOME/NetworkManager-fortisslvpn](https://github.com/GNOME/NetworkManager-fortisslvpn): as far as I know the Gnome plugin does create its own configuration file and could add the certificate if needed. Besides I believe such issues are better handled by a GUI.
> 
> On the other hand I agree an option might help end-users who use _openfortivpn_ directly. To mitigate risks I would recommend:
> 
> * adding a command-line option only, not available from configuration files,
> * such an option would modiy the certificate stored in the configuration file and would then exit, so that it cannot be used on a regular basis when starting _openfortivpn_.
> 
> But again if the CA is unknown, it means the computer has not been properly set up and this should be reported to whomever installed the computer. What it is the use case here? Are you connecting to a corporate or university VPN? Who set up the computer?

Because I don't manage firewalls myself and when the certificate changes (if the primary down for example) the secondary has another certificate. As i said, i'm not an expert so I'm maybe completely wrong but on Windows and Android i don't have this issue (because official clients I suppose).

**Comment by mrbaseman** [comment]
Oh, maybe the official client trusts the built-in Fortinet-CA. FortiOS displays a warning if that certificate is used for the SSL-VPN, but maybe if the admin ignores this warning the client silently accepts the certificate (I haven't verified this hypothesis, but it would explain the observed behavior). 

About the primary and secondary: You can have several `trusted-cert` lines. Just append newly observed ones to your config file. Unless they change the server certificate frequently you should gather the possible digests with a few connection attempts and that's it for the next couple of years.

**Comment by DimitriPapadopoulos** [comment]
Another possibility is that Android and Windows are properly setup, unlike the Linux machine that runs _openfortivpn_.

@woprandi William, you still haven't answered the questions. What it is the use case here? Are you connecting to a corporate or university VPN? Who set up the computers (Linux, Windows, Android)? Also you might want to [retrieve the certificate](https://www.shellhacks.com/get-ssl-certificate-from-server-site-url-export-download/) from the FortiGate appliance and show it here so that we can better understand what's wrong.

**Comment by woprandi** [comment]
@DimitriPapadopoulos It's a corporate VPN. I setup computers (only Linux, we don't use Windows). I only configure through the Gnome plugin UI.

**Comment by DimitriPapadopoulos** [comment]
I'm lost here. You had written that on Windows and Android you “don't have this issue” and now you write that you "don't use Windows". We really need a precise description of your use case.

It would be interesting if indeed _FortClient_ worked out-of-the-box on Windows and Android and _openfortivpn_ didn't on Linux. The reason could be that the Windows and Android systems are properly configured unlike Linux, or that _FortiClient_ operates differently from _openfortivpn_.
* The first hypothesis is that the VPN appliance has a certificate signed by your corporate root CA, and that this this root CA is already installed on corporate Windows and Android systems, but not your Linux computer.Are the Windows computer and Android phone configured by an IT department or yourself? Is there an IT department that can help configure the Linux computer?
* The second hypothesis is that the VPN appliance has a certificate signed by the Fortinet root CA, and that _FortClient_ does trust this Fortinet root CA. If so we could perhaps have _openfortivpn_ trust the the Fortinet root CA too - but I must say this doesn't sound like a very good idea.

We would need you to provide the public certificate of your VPN appliance to verify which hypothesis applies here. Is this something you can do? If you cannot, perhaps could you perhaps provide the hostname / IP address of the VPN appliance so that we can examine the public certificate ourselves?

**Comment by mrbaseman** [comment]
I have done some testing on this with the official client 4.0.2312 on **Linux**. Current linux versions of FortiClient are missing the VPN feature unfortunately.

I have changed the config on my Fortigate to use the "Fortinet_Factory" certtificate for the SSL VPN service (I have to confirm twice in the management gui to change back to this built-in certificate).
The CLI and the GUI of the Forticlient display a similar warning (this is the CLI):
```
STATUS::Setting up the tunnel
STATUS::Connecting...
Certificate:        Version: 3 (0x2)$
        Serial Number: 15757858592399164081 (0xdac636b453c4a56b)$
    Signature Algorithm: sha256WithRSAEncryption$
        Issuer: C=US, ST=California, L=Sunnyvale, O=Fortinet, OU=Certificate Authority, CN=support/emailAddress=support@fortinet.com$
        Validity$
            Not Before: Jul 16 22:34:39 2015 GMT$
            Not After : Jan 19 22:34:39 2038 GMT$
        Subject: C=US, ST=California, L=Sunnyvale, O=Fortinet, OU=Certificate Authority, CN=support/emailAddress=support@fortinet.com$
        Subject Public Key Info:$
            Public Key Algorithm: rsaEncryption$
                Public-Key: (2048 bit)$
                Modulus:$
                    ...                    
                Exponent: 65537 (0x10001)$
        X509v3 extensions:$
            X509v3 Basic Constraints: $
                CA:TRUE$
    Signature Algorithm: sha256WithRSAEncryption$
         ...

The certificate for the SSLVPN server is invalid.
You are connecting to an untrusted server. which could put your confidential information at risk.
Would you like to connect to this server? (Y/N)
```
If I change the configit back to the trusted certificate and I have the CA certificate in the right place, then it connects smoothly.
So, at least in that version the official client does not behave differently than _openfortivpn_

On the Android FortiClient, when I add a new connection there, I see an option "Check server certificate" which is "Disabled" by default :(

**Comment by DimitriPapadopoulos** [comment]
Thank you Martin for your thorough investigations. Therefore in the case of @woprandi the most probable hypothesis is that the VPN appliance has a certificate signed by a corporate CA, and that the Linux machines are not configured to trust this corporate CA.

@woprandi Does this answer your question? Can you ask your IT department to configure the Linux machine? If not I can point you to a page that explains how to add a CA to the list of trusted CAs.

@woprandi We would still need the **public** certificate of your VPN appliance to verify which hypothesis applies here. Can you provide that certificate? If you cannot, could you perhaps provide the hostname or IP address of the VPN appliance so that we can examine the public certificate ourselves?

**Comment by woprandi** [comment]
I'll do some investigations. Thanks for your help.
