### ISSUE TITLE
Changes were made but the version is the same

### ISSUE THREAD

**Issue by sabino** [adrienverge/openfortivpn#541]
I've tried installing using `brew` but I noticed that the latest changes were not included, for instance:
https://github.com/adrienverge/openfortivpn/issues/375

I had to clone and build it myself. Once I've done that, it seems to be working fine.

I'm on macOS 10.15.2

**Comment by DimitriPapadopoulos** [comment]
@sabino What is your question?

#375 is an issue, not a changeset. Perhaps you meant to write #513. Anyway, [_brew_ currently ships _openfortivpn_ 1.11.0](https://formulae.brew.sh/formula/openfortivpn), changes subsequent to _opneofrtivpn_ 1.11.0 are not yet available in a formal version since 1.12.0 has not been released yet.

**Comment by sabino** [comment]
Oh, got it!

Yes, that was my question and yes I meant to refer the #513.
And I've just realized what the Changelog states:

> This high level changelog is usually updated when a release is tagged. On the master branch there may be changes that are not (yet) described here.

https://github.com/adrienverge/openfortivpn/blob/8230c7282405306db2748996d8ef786371af5924/CHANGELOG.md#releases

Anyway, thanks!
