### ISSUE TITLE
DNS issue since version 1.11.0

### ISSUE THREAD

**Issue by Adonist** [adrienverge/openfortivpn#543]
Hi guys,
It seems that when connecting to the VPN since the version 1.11.0 was released, every time we connect to the VPN it writes a 8.8.8.8 DNS on the resolv.conf file.
We are using Centos 7 with Gnome and the packages for NetworkManager-fortisslvpn and NetworkManager-fortisslvpn-gnome but those haven't been updated in ages so I don't think that's the issue.
I tried to force the DNS manually in the connection but then it adds 2 entry for 8.8.8.8 like:

```
nameserver 8.8.8.8
# Generated by NetworkManager
search domain.com
nameserver 10.248.1.216
namesever 8.8.8.8
nameserver 10.248.1.212
```

None of those 8.8.8.8 should exist.
I can provide logs and more information if needed. Thanks

**Comment by DimitriPapadopoulos** [comment]
Note sure how _openfortivpn_ could modify `/etc/resolv.conf` and add `8.8.8.8` without getting this information form the FortiGate appliance.

To start with I would recommend you run the following tests:
1. Run _openfortivpn_ with options `--set-dns=1 --pppd-use-peerdns=0` so that in theory only _openfortivpn_ will attempt to modify `/etc/resolv.conf` based on information sent by the FortiGate appliance - not _pppd_.
2. Run _openfortivpn_ with options `--set-dns=0 --pppd-use-peerdns=1` so that in theory only _pppd_ will attempt to modify `/etc/resolv.conf` based on information sent by the FortiGate appliance - not _openfortivpn_.
3. Run _openfortivpn_ with options `--set-dns=0 --pppd-use-peerdns=0` so that in theory neither _openfortivpn_ nor _pppd_ will attempt to modify `/etc/resolv.conf`. If `/etc/resolv.conf` is still getting modified despite options `--set-dns=0 --pppd-use-peerdns=0`, this issue is probably not directly related to _openfortivpn_.

**Comment by DimitriPapadopoulos** [comment]
Note that _openfortivpn 1.11.0_ did create a slight incompatibility with _NetworkManager-fortisslvpn_, that unfortunately can't be avoided if we want to fix the behaviour of _openfortivpn_:

https://github.com/adrienverge/openfortivpn/issues/503#issuecomment-562207693
[Peer DNS Does not work with OpenFortiVPN 1.11 (#20) · Issues · GNOME / NetworkManager-fortisslvpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/issues/20)

**Comment by Adonist** [comment]
It seems there was a 3rd DNS entry that had 8.8.8.8 in it, but for some reason the order of the DNS entries aren't right.
Yeah we are using NetworkManager-fortisslvpn. Something between the both of them are causing the issues. I had to leave only 1 DNS record for that not happen anymore and still sometimes it appends to the bottom of the file instead of overwriting it's contents (resolv.conf).

**Comment by DimitriPapadopoulos** [comment]
A known issue with _NetworkManager-fortisslvpn_ is that it currently forces `--no-dns` which is a synonym for `--set-dns=0`. The default in versions of _openfortivpn_ prior to 1.11.0 was `--pppd-use-peerdns=1`, resulting implicitly in:
`--set-dns=0 --pppd-use-peerdns=1`
The default starting with _openfortivpn_ 1.11.0 is `--pppd-use-peerdns=0`, resulting implicitly in:
`--set-dns=0 --pppd-use-peerdns=0`
The result is that  `/etc/resolv.conf` is **not** updated when using the current version of  _NetworkManager-fortisslvpn_ with _openfortivpn_ 1.11.0 and later. This is not the issue you're facing here, on the contrary  `/etc/resolv.conf` is updated and too many entries are added.

I believe this is not an _openfortivpn_ issue, rather a _NetworkManager-fortisslvpn_ or _pppd_ issue. Note that [_NetworkManager-fortisslvpn_ has been patched on Fedora / EPEL]( https://bugzilla.redhat.com/show_bug.cgi?id=1785601). As far as I can see the patch adds the `--pppd-use-peerdns=1` parameter which results again in:
`--set-dns=0 --pppd-use-peerdns=1`
instead of:
`--set-dns=0 --pppd-use-peerdns=0`
It is important you check which exact version of _NetworkManager-fortisslvpn_ you're using to find if it is patched or not:
* If you are using a non-patched version of _NetworkManager-fortisslvpn_ with _openfortivpn_ 1.11.0, neither _openfortivpn_ nor _pppd_ should modify `/etc/resolv.conf` so the problem is somewhere in _NetworkManager-fortisslvpn_ parameters, check your configuration.
* If you are using a patched version of _NetworkManager-fortisslvpn_ with _openfortivpn_ 1.11.0, then _pppd_ is supposed to to modify `/etc/resolv.conf` but again it should only add DNS servers as instructed by the FortiGate appliance.

I suggest :
1. Run _openfortivpn_ in full verbose mode (`--set-dns=1 --pppd-use-peerdns=0 -v -v -v -v`) and check what the FortiGate appliance instructs _openfortivpn_ to do. Look for something like this in the _openfortivpn_ log:
```
<?xml version='1.0' encoding='utf-8'?><sslvpn-tunnel ver='2' dtls='1' patch='1'>[...]<dns ip='xxx.xxx.xxx.xxx' /><dns ip='xxx.xxx.xxx.xxx' />[...]</sslvpn-tunnel>
```
2. Run _openfortivpn_ with `--set-dns=0 --pppd-use-peerdns=1 --pppd-log=...` and check what _pppd_ does.  Look for something like this in the _pppd_ log:
```
primary DNS address xxx.xxx.xxx.xxx
secondary DNS address xxx.xxx.xxx.xxx
```

**Comment by DimitriPapadopoulos** [comment]
@Adonist Were you able to sort this out? Did the above help a little bit and have you been able to find whether this is related to _pppd_ or maybe _NetworkManager_ itself?

**Comment by DimitriPapadopoulos** [comment]
@Adonist Which exact _NetworkManager-fortisslvpn_ are you running? Can you run the following command and shod the output?
```
rpm -qa | grep NetworkManager
```

**Comment by Adonist** [comment]
Hi @DimitriPapadopoulos 
The issue still persists. The issue is probably through NetworkManager-fortisslvpn though.
It's receiving the the right DNS records but not being able to update the file anymore. I've been having to set up them manually. It seems there's an update for that but I have to double check on the machines having issues if they have the newest version from the EPEL repo.
I think the NetworkManager-fortisslvpn isn't being able to handle 3 records coming from the vpn either and trying to force it through the manual input in the configuration isn't helping.
I will test further and contact them anyway.
I'm happy for you to close this as it's clearly not an issue with openfortivpn.
Thank you very much for you help!

**Comment by DimitriPapadopoulos** [comment]
> The issue still persists. The issue is probably through NetworkManager-fortisslvpn though.
> It's receiving the the right DNS records but not being able to update the file anymore. I've been having to set up them manually. It seems there's an update for that but I have to double check on the machines having issues if they have the newest version from the EPEL repo.

That has to be related to the _openfportivpn_ ≥ 1.11.0 issue I have been referring to;
https://bugzilla.redhat.com/show_bug.cgi?id=1785601

The combination with previous versions of _NetworkManager_fortisslvpn_, probably **<&nbsp;`NetworkManager-fortisslvpn-1.2.8-6.el7`**, results in `--set-dns=0 --pppd-use-peerdns=0` by default (implicitly if not explicitly). The result is that **`/etc/resolv.conf` is not updated** by default (at least not by _openfortivpn_ or _pppd_).

The combination with the most recent versions of _NetworkManager-fortisslvpn_, probably **≥&nbsp;`NetworkManager-fortisslvpn-1.2.8-6.el7`**, results in `--set-dns=0 --pppd-use-peerdns=1` by default (explicitly). The result is that by default **_pppd_ is supposed to update `/etc/resolv.conf`**.

That's why I recommend you check and report the current version of _NetworkManager-fortisslvpn_, so that we know which case we're in:
```
rpm -qa | grep NetworkManager-fortisslvpn
```

> I think the NetworkManager-fortisslvpn isn't being able to handle 3 records coming from the vpn either and trying to force it through the manual input in the configuration isn't helping.

OK. So the FortiGate device does send 3 records to _openfortivpn_ - do you see them in the _openfortivpn_ log if you run _openfortivpn_ manually?

If you specify the 3 DNS servers manually in _NetworkManager_ (probably what you have ended up doing if using <&nbsp;`NetworkManager-fortisslvpn-1.2.8-6.el7), chances are it's indeed a _NetworkManager_ issue which does not set the DNS records as requested.

Now if you do **not** specify the 3 DNS servers manually in _NetworkManager_ (you should be able to do that **only** if using ≥&nbsp;`NetworkManager-fortisslvpn-1.2.8-6.el7), then you should be back in the default situation prior to _openfortivpn_ 1.11.0, where _NetworkManager-fortisslvpn_ lets _pppd_ handle the DNS records. This should work again if it used to work before upgrading _openfortivpn_.

**Comment by DimitriPapadopoulos** [comment]
@Adonist Time permitting, could you report which case you fall in, said otherwise which exact version of _NetworkManager-fortisslvpn_ you're using?
