### ISSUE TITLE
"could not set route to tunnel gw" error in Ubuntu 16.04

### ISSUE THREAD

**Issue by jjamor** [adrienverge/openfortivpn#55]
Hello,

I recently upgraded to Ubuntu 16.04. Since that upgrade, I cannot connect using openfortivpn because:

```bash

DEBUG:  ip route add to 0.0.0.0/106.127.0.0 dev ppp0
WARN:   Could not set route to tunnel gateway (Address family not supported by protocol).
```

May be linux version (4.4.0)?

Could you help us?

Thanks!

**Comment by adrienverge** [comment]
Hi,

I don't have access to a Fortinet VPN anymore so I can't help you here.

Any help from anyone is welcome!

**Comment by mata-p** [comment]
I noticed the same, I think the cause is that [here](https://github.com/adrienverge/openfortivpn/blob/eeac196193e03ba1903193f5167d28879c6b601a/src/tunnel.c#L408) `tunnel.ipv4.split_routes` is not inizialized to 0.
Another manifestation of the same I noticed was a buffer overflow which crashed the program [here](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L211)

    char env_var[21];
    // ...
    sprintf(env_var, "VPN_ROUTE_DEST_%d", tunnel->ipv4.split_routes);

because the value was too big to fit into env_var. Initializing the variable to 0 fixes that.
To be safe I blanketed the whole struct before using it with

    memset(&tunnel, 0, sizeof(tunnel));

**Comment by jjamor** [comment]
Hi @mata-p , many thanks!

I just tested your change, and it works!

Can you generate a pull request?

Thanks!

**Comment by adrienverge** [comment]
I just pushed a fix to `master`, many thanks to @mata-p for finding the cause!
