### ISSUE TITLE
run in background ?

### ISSUE THREAD

**Issue by txsastre** [adrienverge/openfortivpn#594]
hi there, thanks for this marvellous tool

I'm trying to do a lightweight distro for our users, and this is going to be very helpful.

but I'm trying to start a tunnel, and it works, but it does not "leave" the console it stays in foreground saying 
INFO:   Tunnel is up and running.

but I would like to be able to start and RDP connection, but it does not start because it is "stopped" by the openfortivpn 

may be I'm missing something but I don't find it !

thanks

**Comment by DimitriPapadopoulos** [comment]
Indeed _openfortivpn_ is not a "daemon" or service that you start and forget. It's a program launched from the command line and you want it running in a console so that you can stop it with Ctrl+C. That's by design. As an alternative you may use _NetworkManager-fortisslvpn_ available on many Linux distributions.

Not sure what you mean about the RDP connection being "stopped" by _openfortivpn_. Are you writing  a script and do you call `openfortivpn` and the some other command so start RDP but that command is not reached because the script gets stock on the `openfortivpn` command until it exits? If so that's indeed teh case. It's up to you write a more complex script to handle that.

**Comment by txsastre** [comment]
hi there.

well, the idea was to create a debian distro (with no desktop) for users who have problem with their computers or they are to old, to stablish an vpn connection and then open an RDP conection against our servers.

the concept is :
- start debian with no desktop
- execute bash
------- openfortivpn -c my_config 
------- rdesktop 192.168.1.1

but when executing "openfortivpn -c my_config " the bash script does not continue to the rdesktop connection, because I can see on the screen a successful vpn.

hope I have explained properly my problem.

Thanks

**Comment by txsastre** [comment]
hi again
I've used this solution : 
sudo openfortivpn -c my_config **> program.log 2>&1**

**Comment by DimitriPapadopoulos** [comment]
Yes, as long as you don't need to enter a password or other identifiers interactively, you may launch `openfortivpn` in the background yourself. By the way, you may have forgotten an extra **`&`**:
* `sudo openfortivpn -c my_config` starts openfortivpn with all parameters in a configuration file
* `> program.log 2>&1` redirects _stdout_ and _stderr_ to `program.log` (perhaps `openfortivpn.log` is better by the way)
* you probably need a final `&` to start in the background.

That said, how do you stop _openfortivpn_ (never?) and how do you restart it if needed (reboot?)?

**Comment by txsastre** [comment]
hi, I have some issues making it work in background but finally I get it working.
The idea is to have an ISO with a Debian with not GUI, a way to have an thinclient that it connects with VPN to our RDP servers.
it's going to be helpful this strange days, and later it will be useful for our remote users or small sites that they don't have an VPN capable firewall.
so the idea is to put de CD, start the PC, connect vpn, connect RDP, and when logged out from remote RDP then shutdown the PC.

**Comment by DimitriPapadopoulos** [comment]
Thinking about it again:
* You may not be using the right tools for the purpose. Linux machines have other mechanisms such as _init_ or _systemd_ to start things after booting. I fully appreciate you're in a hurry, just suggesting this is perhaps not a long term solution. For example what happens if _openfortivpn_ fails and needs to be restarted? Reboot? Starting with a mere script, chances are you'll end up reinventing the wheel.
* Currently there is no `--background` option in _openfortivpn_ or anything that would provide the requested functionality.
* While I do see the use case, I am not in favour of a `--background` option: _openfortivpn_ would need to be modified to stay in the foreground for the initial interactive part then fork to the background or something like that when the tunnel is up. I fear this will add lots of complexity and introduce more bugs, I would prefer _openfortivpn_ to focus on its core functionality and do it well instead of adding belles and whistles.

That said I'm not against the functionality. I would like to keep it outside of the C source code if possible at all, for the sake of simplicity and maintainability:
* The same functionality could be achieved by running _openfortivpn_ in the background from start if no interaction is needed - from the shell or using _systemd_ for example.
* Switching to the background just after the tunnel is operational could be achieved by a wrapper script in Python or something similar - if I'm not mistaken.

@txsastre For these reasons my gut feeling would be to close this issue. What do you think?

**Comment by mrbaseman** [comment]
if no interactive password is needed (e.g. password stored in the config file) and no token input is needed either, the `--persistent` option in conjunction with sending the process to the background on the shell (by appending a `&` to the command line) might be an easy solution to reconnect when the VPN interrupted

**Comment by juarezr** [comment]
I've built a systemd hardened service file for running in background.

This way I can manually start/stop the service with:
``` bash
$ sudo systemctl start openfortivpn
$ systemctl status openfortivpn
$ sudo systemctl stop openfortivpn
$ sudo systemctl restart openfortivpn
```
Or can automatically enable with:
``` bash
$ sudo systemctl enable openfortivpn
```

Anyone knows if there any issue of bundling this with installation packages/bundles?

## The service unit file:

```
[Unit]
Description=Openfortivpn VPN service.

After=network-online.target
Wants=network-online.target

StartLimitIntervalSec=300
StartLimitBurst=5

Documentation=man:openfortivpn(1)

[Service]
Type=simple

ExecStart=/usr/bin/openfortivpn --persistent=5
Restart=on-failure
RestartSec=5s

DeviceAllow=/dev/ppp
ReadWritePaths=/var/run

# security and hardening options for systemd service units
# https://gist.github.com/ageis/f5595e59b1cddb1513d1b425a323db04

PrivateTmp=yes
DevicePolicy=closed

#~ TODO:
#~ DynamicUser=yes
#~ PrivateUsers=yes
#~ PrivateDevices=yes

NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
ProtectHostname=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes

# Newer systemd versions allow:
#~ ProtectKernelLogs=yes
#~ ProtectClock=yes

RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
MemoryDenyWriteExecute=yes
LockPersonality=yes

# SIOCSIFADDR SIOCSIFFLAGS SIOCSIFMTU
SystemCallFilter=@system-service @network-io

[Install]
WantedBy=multi-user.target

# end of the file #
```

**Comment by huancz** [comment]
```screen -d -m -s openfortivpn openfortivpn```
Starts in background, doesn't block script execution, but you can still reattach (`screen -r openfortivpn`) and supply interactive auth, or diagnose in case of problems. You may need to insert sleep somewhere in the script to allow the client to connect before launching rdesktop.

It's not universal solution to all daemon problems, just another tool in the box. Highly useful tool.

**Comment by txsastre** [comment]
hi there everyone.

thanks for your post trying to solve the situation.

I solved the problem days ago, but I was to busy to respond to you, sorry.
finally I decided that the VPN was going to be a not a fixed hard-coded connection, to avoid security problems. 

Once the  live-CD runs, it asks for user & password which is used to establish the VPN and stores it in a file, the it tries to set the VPN on, if its successful, then the script launches xfreerdp with the user and password parameters previously stored and the user log in the remotes session SSO style.

as it is a live-cd nothing is stored in it nor the computer.

it works and we have solved the problem almost for two users (by now). Also it is useful as a contingency plan.


code that establish VPN (sorry Im unable to show it as code formatted)
VPNFILE="./vpnsettings.conf"
HOST="host = my.server.net"
PORT="port = 9443"
TRUSTED="trusted-cert = cdf4787b123456dcadca19008c3b44f614157fd4ea5da6bd4926047a794647f9"
USERNAME="username = "
PASSWORD="password = "
VPNON=""
while [ -z "$VPNON" ]
do
    echo
	echo -e "\e[39mIntroduïu les vostres credencials"
	echo -e "================================="
    echo
	read -e -p "Usuari:"  USERNAME
	USERNAME="username = $USERNAME"
	echo -n "Contrasenya":
	read -s PASSWORD
	PASSWORD="password = $PASSWORD"
	echo ""
	echo "Configurant"
	echo $HOST > $VPNFILE
	echo $PORT >> $VPNFILE
	echo $USERNAME >> $VPNFILE
	echo $PASSWORD >> $VPNFILE
	echo $TRUSTED >> $VPNFILE
    echo
	echo "Establint connexió VPN"
	VPNON=""
    sudo openfortivpn -c $VPNFILE > openfortivpn.log 2>&1 &
   COUNT=1
    while [ -z "$VPNON" ]
	do
	    echo -ne "\e[33mCONNECTANT VPN ... $COUNT\033[0K\r"
		VPNON='ip a | grep ppp0'
		if [ ! -z "$VPNON" ]
		then
            echo
			echo -e "\e[32mVPN. Ok "
			break
		fi
		if [ $COUNT -eq 10 ];
		then
			echo ""
			echo ""
			echo -e "\e[31mERROR: No s'ha pogut connectar la VPN. "
			break
		fi
		let COUNT=$COUNT+1
		sleep 1
	done
done

code that launches Xfreerdp



VPNFILE="./vpnsettings.conf"'
username='cat $VPNFILE | grep username | cut -d ' ' -f 3'
password='cat $VPNFILE | grep password | cut -d ' ' -f 3'
xfreerdp /f /kbd:0x0000040A /d:domain /u:"$username" /p:"$password" /multimon /sound:sys:alsa /v:$SERVERRDP

**Comment by DimitriPapadopoulos** [comment]
@txsastre Thank you for coming back to us with your solution. I'm closing this issue but feel free to re-open or open a new one if needed.

**Comment by Perlovka** [comment]
Here is openrc script for running as a service with OTP password
It asks user for both passwords and then start openfortivpn as a service in background.

```
#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start_pre() {
    read -sp 'Password: ' user_pwd
    echo
    read -sp 'OTP: ' user_otp
    echo
}

start() {
	ebegin "Starting openfortivpn"

	start-stop-daemon --start --quiet -m -b \
		--pidfile "/var/run/openfortivpn.pid" \
		-1 /var/log/openfortivpn.log \
		-2 /var/log/openfortivpn.err.log \
		--exec /usr/bin/openfortivpn -- -p "$user_pwd" -o "$user_otp" --otp-delay=2
	eend $?
}

stop() {
	ebegin "Stopping openfortivpn"
	start-stop-daemon --stop --quiet --pidfile "/var/run/openfortivpn.pid"
	eend $?
}
```

**Comment by txsastre** [comment]
thanks, don't know when I will have time to try it, but good to know !!

**Comment by DimitriPapadopoulos** [comment]
@Perlovka Starting with #747 and _openfortivpn_ 1.15, the password won't be visible in the process list - or rather will be visible only transiently when starting _openfortivpn_.
