### ISSUE TITLE
SmartCard + username and password

### ISSUE THREAD

**Issue by simowdas** [adrienverge/openfortivpn#629]
Version: 1.12.0
When using username,password and user-cert from smartcard the username and pass are not send to server.

/remote/login is send only cert=&nup=1

**Comment by DimitriPapadopoulos** [comment]
Ins't this a duplicate of #507?

**Comment by DimitriPapadopoulos** [comment]
Or perhaps not because #507 is supposed to have been fixed in 1.12.0.

**Comment by DimitriPapadopoulos** [comment]
It would help if you could show the (sanitized) output of `openfortivpn -v -v` and the (sanitized) contents of `/etc/openfortivpn/config`.

**Comment by simowdas** [comment]
`DEBUG:  openfortivpn 1.12.0                                                                                                                                                                     [66/801]
DEBUG:  Loaded config file "/etc/openfortivpn/config".                                                                                                                                                  
DEBUG:  Loaded password from config file "/etc/openfortivpn/config"                                                                                                                                     
DEBUG:  Config host = "***"                                                                                                                                                                             
DEBUG:  Config realm = "someone"                                                                                                                                                                        
DEBUG:  Config port = "443"                                                                                                                                                                             
DEBUG:  Config username = "someone"                                                                                                                                                                     
DEBUG:  Resolving gateway host ip                                                                                                                                                                       
DEBUG:  Establishing ssl connection                                                                                                                                                                     
DEBUG:  server_addr:*****                                                                                                                                                                               
DEBUG:  server_port: 443                                                                                                                                                                                
DEBUG:  gateway_addr: ******                                                                                                                                                                            
DEBUG:  gateway_port: 443                                                                                                                                                                               
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4                                                                                                                                   
DEBUG:  Gateway certificate validation failed.                                                                                                                                                          
DEBUG:  Gateway certificate digest found in white list.                                                                                                                                                 
INFO:   Connected to gateway.                                                                                                                                                                           
DEBUG:  http_send:                                                                                                                                                                                      GET /remote/login HTTP/1.1                                                                                                                                                                              Host: ***********:443                                                                                                                                                                                   User-Agent: Mozilla/5.0 SV1                
Accept: text/plain                                
Accept-Encoding: identity                                                                           
Content-Type: application/x-www-form-urlencoded
Cookie: 
Content-Length: 11

cert=&nup=1
DEBUG:  http_receive:
HTTP/1.1 200 OK
Date: Tue, 07 Apr 2020 10:24:56 GMT
Server: xxxxxxxx-xxxxx
Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
X-UA-Compatible: requiresActiveX=true
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

ec0   
<!DOCTYPE html><html lang="en" class="main-app"> <head> <meta charset="UTF-8"> <meta http-equiv="X-UA-Compatible" content="IE=8; IE=EDGE"> <meta name="viewport" content="width=device-width, initial-sc
<some HTML here>


E5 18 C3 5F AC F6 8A 88 28 46 7E 1B 15 4E 4F 66 ..._....(F~..NOf
EB AB F3 33 00 11 C6 61 51                      ...3...aQ

ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
DEBUG:  No cookie given -7
INFO:   Closed connection to gateway.
`

Config:
`host = vpn.server.pl
port = 443
user-cert = pkcs11:

username = someone
password = somepass
realm = someone
trusted-cert = 9gad786876dagu0f15934d965023574db9ea157cdd05`

**Comment by DimitriPapadopoulos** [comment]
The config file looks OK.

**Comment by mrbaseman** [comment]
we [currently support ](https://github.com/adrienverge/openfortivpn/blob/18145748ff08f8d4da3f9b4386ae4e7cc85050aa/src/http.c#L582)
- smart card _or_ user certificate without username&password 
- user certificate and username&password
- username&password
optionally one time password in addition to the above combinations.

We could try to handle your case differently. The problem is that without smartcard username and password are sent via http post, but with smartcard a GET is used and I don't know if we just can pass the posted parameters together with this get-request or if we should switch to post in that case. 
Do you have the chance to watch what Forticlient does in this scenario? Maybe the `!!!!some HTML here!!!!!!` section is interesting. Just make sure to anonymize sensitive data therein.

**Comment by mrbaseman** [comment]
Actually, the case "user certificate and username&password" is very close to yours, except that the certificate is stored on the smart card. Historically, the case to log in without username&password came into the source together with the pull request for smart card support in #464. 
But maybe the distinction if username and password are empty (which came later in the code) is good enough there. 
@simowdas can you try if [my smartcard branch](https://github.com/mrbaseman/openfortivpn/tree/smartcard) works for you?

**Comment by mrbaseman** [comment]
I have created pull request #631 but I would like to have verified that it solves your problem and verified that it does not severely break a working feature for others

**Comment by simowdas** [comment]
> I have created pull request #631 but I would like to have verified that it solves your problem and verified that it does not severely break a working feature for others

I've checked You fix and it's working. Thx

**Comment by NicoB48** [comment]
Hello,

I'm trying to use use this specific mode for 2 months (Client Cert hosted on Yubikey + User + Password) but I was unable to achieve it. I tried, with or without dummy entries. 

If I provide a file instead of pkcs11, It works.

So, in my mind, it's not solved.

host = myhost.domain
port = 443
username = adminNico
trusted-cert = 9f40b40xxxxxxxxxxxxxxxxxxxx7608d40c
user-cert = pkcs11:serial=xxxxxxxxxxxx;id=%01

sudo openfortivpn -v -v -v -v --no-dns --no-routes
DEBUG:  ATTENTION: the output contains sensitive information such as the THE CLEAR TEXT PASSWORD.
DEBUG:  openfortivpn 1.12.0
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Disabled password due to empty entry in config file "/etc/openfortivpn/config"
DEBUG:  Config host = "myhost.domain"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG: Config username = "adminNico"
DEBUG:  Config password = ""
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: x.x.x.x
DEBUG:  server_port: 443
DEBUG:  gateway_addr: x.x.x.x
DEBUG:  gateway_port: 443
Enter PKCS#11 token PIN for adminNico :
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
DEBUG:  http_send:
GET /remote/login HTTP/1.1
Host: myhost.domain:443
User-Agent: Mozilla/5.0 SV1
Accept: text/plain
Accept-Encoding: identity
Content-Type: application/x-www-form-urlencoded
Cookie: 
Content-Length: 11

cert=&nup=1
DEBUG:  http_receive:
HTTP/1.1 200 OK
**** SOME HTML ****
ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
DEBUG:  No cookie given -7
INFO:   Closed connection to gateway.
