### ISSUE TITLE
openfortivpn 1.14.0 Hangup (SIGHUP) on Catalina

### ISSUE THREAD

**Issue by skycaptain** [adrienverge/openfortivpn#715]
After updating from 1.13.3 to 1.14.0 via homebrew I can not connect to my company's VPN network. The connection is terminated right after VPN nameservers are added:

```
...
INFO:   Interface ppp0 is UP.
INFO:   Adding VPN nameservers...
DEBUG:  Attempting to modify /etc/resolv.conf directly.
DEBUG:  Adding "nameserver 192.168.100.100", to /etc/resolv.conf.
DEBUG:  Adding "nameserver 192.168.100.101", to /etc/resolv.conf.
DEBUG:  Adding "search XXXX.de", to /etc/resolv.conf.
Sun May 17 18:42:00 2020 : Hangup (SIGHUP)
Sun May 17 18:42:00 2020 : Modem hangup
Sun May 17 18:42:00 2020 : Connection terminated.
Sun May 17 18:42:00 2020 : LCP close (User request).
Sun May 17 18:42:00 2020 : Connect time 0.0 minutes.
Sun May 17 18:42:00 2020 : Sent 1249 bytes, received 2362 bytes.
fish: 'sudo openfortivpn --config ~/.c…' terminated by signal SIGILL (Illegal instruction)
```

Version 1.13.3 still works fine with the same config.

**Comment by DimitriPapadopoulos** [comment]
Yuck. The most invasive change in 1.14.0 is 5574b45296e26ebdb25a8824f003d69a75b6f609, I hope it is not responsible for that.

If you feel comfortable retrieving _openfortivpn_ with `git` and compiling it, perhaps youy can try  before/after 5574b45296e26ebdb25a8824f003d69a75b6f609.

Otherwise doesn't macOS generate a crash report?

Finally any special options in your configuration file?

**Comment by skycaptain** [comment]
I did a git bisect and it seems like c81fde1aa474108ba5c0b74e66b9e91a2a41b5e1 is the culprit. Would make sense since the crash happens right after adding nameservers to `/etc/resolv.conf`. I then reverted that change ontop of master and did another build. It worked.

**Comment by DimitriPapadopoulos** [comment]
Strange, are you certain it's not a171722afbc0be0355b2ae920a4fb38ccd8c757c, immediately following c81fde1aa474108ba5c0b74e66b9e91a2a41b5e1?

We know a171722afbc0be0355b2ae920a4fb38ccd8c757c was responsible for a segfault but it has been fixed by f234c5f2650d23daeaeac37b632571e86226861c.

**Comment by DimitriPapadopoulos** [comment]
Let's have one more look at c81fde1aa474108ba5c0b74e66b9e91a2a41b5e1 though:

1. I changed:
   ```
   char line[57]; // 1 + 15 + 7 + 15 + 2 + 15 + 1 + 1
   ```
   into:
   ```
   char line[ARRAY_SIZE("[xxx.xxx.xxx.xxx], ns [xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx]")];
   ```
   I have check with a [test program](https://gist.github.com/DimitriPapadopoulos/7ea5340c94c16c802367e6b42e7e2af3) that `ARRAY_SIZE("[xxx.xxx.xxx.xxx], ns [xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx]")] == 57`
2. Then I changed:
   ```
   char ns1[28], ns2[28]; // 11 + 15 + 1 + 1
   ```
   into:
   ```
   static const size_t NS_SIZE = ARRAY_SIZE("nameserver xxx.xxx.xxx.xxx");
   char ns1[NS_SIZE], ns2[NS_SIZE];
   ```
   Again I had used a test program and had noticed that `ARRAY_SIZE("nameserver xxx.xxx.xxx.xxx") == 27`. I though it was OK though. Perhaps I need to look into this in more detail. Why would we need 28 instead of 27?
3. Finaly I changed:
   ```
   char dns_suffix[MAX_DOMAIN_LENGTH+8];  // 7 + MAX_DOMAIN_LENGTH + 1
   ```
   into:
   ```
   static const size_t DNS_SUFFIX_SIZE = ARRAY_SIZE("search ") + MAX_DOMAIN_LENGTH;
   char dns_suffix[DNS_SUFFIX_SIZE];
   ```
   This one's OK.

**Comment by DimitriPapadopoulos** [comment]
About this one, I think it should have been 27 instead of 28 from the beginning:
```
char ns1[28], ns2[28]; // 11 + 15 + 1 + 1
```
Otherwise the comment doesn't make sense. In `11 + 15 + 1 + 1`:
* 11 is supposed to be the length of `nameserver`, which is actually 10,
* 15 is the length of an IPv4 address,
* the first 1 is for the space between `nameserver` and the IPv4 address,
* the second 1 is for the terminal null character.

Therefore I don't see any error in c81fde1aa474108ba5c0b74e66b9e91a2a41b5e1.

**Comment by skycaptain** [comment]
c81fde1aa474108ba5c0b74e66b9e91a2a41b5e1 is was git bisect between 2d89a16943ed043703b9218da4fc2f8ca02d511c and e008b7b8be55f1433f428bc6088063f6343409b7 gave me. I tested a171722afbc0be0355b2ae920a4fb38ccd8c757c and f234c5f2650d23daeaeac37b632571e86226861c; both failed with the same error. 547228d80e6ed2c7a88f51a04e367f3282d9938e worked fine.

If I run the latest master with `--no-dns` everything works, so it has to be related to these changes somehow.

I run the command with debugger and it crashed at this line: https://github.com/adrienverge/openfortivpn/blob/e008b7b8be55f1433f428bc6088063f6343409b7/src/ipv4.c#L1233

**Comment by DimitriPapadopoulos** [comment]
No debugging needed :-) The code you've outlined is enough.

Actually `11 + 15 + 1 + 1` means:
* 11 is the length of `nameserver  ` **with the space**,
* 15 is the length of an IPv4 address,
* the first 1 is for the `\n` I had forgotten,
* the second 1 is for the terminal null character.
So it's 28 indeed, not 27.
