### ISSUE TITLE
unable to verify cert that other tools say is OK

### ISSUE THREAD

**Issue by bremner** [adrienverge/openfortivpn#726]
The attached certificate is not verified by openfortivpn (1.14.1). 

I checked it it with firefox, chromium, and ssl-cert-check for host sslvpn1.unb.ca:10443 and they all seemed OK with it.

I added 
```
ca-file = /etc/ssl/certs/ca-certificates.crt
```
to /etc/openfortivpn/config (and tried the equivalent command line option) but it did not seem to help.

I understand if other peoples SSL is no fun to debug, but I thought I'd report it in case I was missing something obvious.

[crt.txt](https://github.com/adrienverge/openfortivpn/files/4695838/crt.txt)

**Comment by DimitriPapadopoulos** [comment]
I'm not very knowledgeable but it looks like there is some kind of problem with the certificate:
```
$ curl --verbose 'https://sslvpn1.unb.ca:10443/remote/login?lang=en'
*   Trying 198.164.163.50:10443...
* TCP_NODELAY set
* Connected to sslvpn1.unb.ca (198.164.163.50) port 10443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
$ 
```
I'll try to look into the details.

**Comment by DimitriPapadopoulos** [comment]
The certificate is indeed recognized by most browsers, but that's because browsers tend to complete incomplete certification chains using intermediate certificates they might have in their store. This is covered by [Get your certificate chain right](https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce) for example.

You could ask the IT support of you organisation to add the missing intermediate certificates to their VPN gateways - or instead work around the missing certificates:
* tell _openfortivpn_ to trust the incomplete certificate using `--trusted-cert`,
* create an alternative CA certificate bundle from the store of a browser that trusts the certificate of your VPN gateway and use instead of the system CA certificate bundle used by OpenSSL by default (`/etc/ssl/certs/ca-certificates.crt` on Ubuntu) and feet that bundle to _openfortivpn_ using `--ca-file`. See example below.

#### Example of workaround on Ubuntu 20.04

1. Create an alternative CA certificate bundle as described in [CA certificates extracted from Mozilla](https://curl.haxx.se/docs/caextract.html):
   ```
   $ sudo apt install libnss3-tools
   [...]
   Unpacking libnss3-tools (2:3.49.1-1ubuntu1) ...
   Setting up libnss3-tools (2:3.49.1-1ubuntu1) ...
   Processing triggers for man-db (2.9.1-1) ...
   $ 
   $ wget -q https://raw.githubusercontent.com/curl/curl/master/lib/firefox-db2pem.sh
   $ 
   $ chmod +x firefox-db2pem.sh
   $ 
   $ ./firefox-db2pem.sh
   $ 
   $ ls -l ca-bundle.crt 
   -rw-rw-r-- 1 xxxxxxx xxxxxxx 457434 May 28 18:17 ca-bundle.crt
   $ 
   ```
2. Feed the alternative CA certificate bundle to _openfortivpn_ using `--ca-file`:
   ```
   $ sudo openfortivpn --ca-file=ca-bundle.crt -u user sslvpn1.unb.ca:10443
   VPN account password: 
   INFO:   Connected to gateway.
   ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
   INFO:   Closed connection to gateway.
   INFO:   Logged out.
   $ 
   ```
3. Compare to the system CA certificate bundle:
   ```
   $ sudo openfortivpn --ca-file=/etc/ssl/certs/ca-certificates.crt -u user sslvpn1.unb.ca:10443
   VPN account password: 
   ERROR:  Gateway certificate validation failed, and the certificate digest is not in the local whitelist. If you trust it, rerun with:
   ERROR:      --trusted-cert ac7a818cb28d0747104750620fdc0681c37fb589b7c209f3959e8cad9c5368cc
   ERROR:  or add this line to your config file:
   ERROR:      trusted-cert = ac7a818cb28d0747104750620fdc0681c37fb589b7c209f3959e8cad9c5368cc
   ERROR:  Gateway certificate:
   ERROR:      subject:
   ERROR:          CN=sslvpn.unb.ca
   ERROR:      issuer:
   ERROR:          C=GB
   ERROR:          ST=Greater Manchester
   ERROR:          L=Salford
   ERROR:          O=Sectigo Limited
   ERROR:          CN=Sectigo RSA Domain Validation Secure Server CA
   ERROR:      sha256 digest:
   ERROR:          ac7a818cb28d0747104750620fdc0681c37fb589b7c209f3959e8cad9c5368cc
   INFO:   Closed connection to gateway.
   [...]
   ```

**Comment by DimitriPapadopoulos** [comment]
I don't think we can do much more on our side, as it's not our role to feed CA certificates to end-users. This has to be fixed locally in your organisation, either by fixing the incomplete certificates in the VPN gateways, or by adding the missing intermediate certificates in the store of client computers.

**Comment by bremner** [comment]
Dimitri Papadopoulos Orfanos <notifications@github.com> writes:

> I don't think we can do much more on our side, as it's not our role to
> feed CA certificates to end-users. This has to be fixed locally in
> your organisation, either by fixing the incomplete certificates in the
> VPN gateways, or by adding the missing intermediate certificates in
> the store of client computers.

OK, thanks for looking into it, and for the detailed explanation.
