### ISSUE TITLE
MDNS not working with --no-dns option

### ISSUE THREAD

**Issue by emericv** [adrienverge/openfortivpn#739]
Hello!

when openfortivpn is started with --no-dns, the MDNS is not functional. I don't know why exactly.
This issue origin is that this client is run by NetworkManager-fortisslvpn with --no-dns option which break MDNS functionning.
For this test, I have launched the command in the same way as NetworkManager-fortisslvpn plugin and whithout --no-dns option, MDNS requests work...
Any idea ?

Thanks

**Comment by DimitriPapadopoulos** [comment]
NetworkManager-fortisslvpn runs _openfortivpn_ with `--no-dns` because DNS and routing are handled by NetworkManager-fortisslvpn. Therefore this not an _openfortivpn_ issue, try NetworkManager-fortisslvpn instead:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn

Also I don't see how `--no-dns` could "break" mDNS.. What do you mean exactly when you write that mDNS is "broken"? It could be that the VPN gateway requests your machine is insulated from the local network, in which case mDNS multicast may not be able to reach local machines - by construction. But then you probably don't need mDNS since you cannot reach the local network anyway. Unless you expect mDNS queries to resolve remote machines?

**Comment by emericv** [comment]
In fact `NetworkManager-fortisslvpn` did the work correctly and I have just indicate it for the context. In my case I feared that the `--no-dns` option causes a side effect on MDNS functioning but finally is not the case here. The real issue is elsewhere.

I close this issue (invalid)
