### ISSUE TITLE
Can't connect to VPN

### ISSUE THREAD

**Issue by rtargino** [adrienverge/openfortivpn#784]
Hello everyone.

I've been smoothly using openfortivpn for a while on Ubuntu 20.04 until changing the motherboard of my laptop, after which openfortivpn stopped working. I'm not sure if there is any relationship between these two things, but I had several issues after changing the board...

When calling openfortivpn from the terminal, it seems to connect (no errors) but my IP doesn't change and I can't connect to my company's webpage.

I'm attaching the -v -v output, with some information replaced by the word REMOVED.

[temp.txt](https://github.com/adrienverge/openfortivpn/files/5283466/temp.txt)

Any help or directions are appreciated! :)

**Comment by DimitriPapadopoulos** [comment]
There are no errors between these lines of the log, so I don't really know at this point:
```
INFO:   Tunnel is up and running.
```
```
INFO:   Cancelling threads...
DEBUG:  disconnecting
INFO:   Setting ppp interface down.
```

How exactly does _openfortivpn_ not work? Does _openfortivpn stop by itself?

**Comment by rtargino** [comment]
Thanks for the prompt reply, @DimitriPapadopoulos .

I'm getting 404 errors when I try to access a website inside my company's network and I'm sure everything is up and running, as other people can access it normally.

Sorry for the silly question, but is there a more definitive way to check if the VPN is actually working? Answering your question, no, openfortivpn does not stop by itself.

**Comment by DimitriPapadopoulos** [comment]
Then the core functionality of _openfortivpn_ probably does work. What does not work is routing and DNS settings.

Most probably in this case it's a DNS problem. I see that a `resolvconf` command is available but it's probably a broken one. To verify that, attempt to access a server using its IP address instead of its DNS name.

**Comment by rtargino** [comment]
Hi @DimitriPapadopoulos , I still can't get my head around what's going on...

I followed the suggestion from here: https://github.com/pop-os/pop/issues/773
and run
`sudo dpkg-reconfigure resolvconf`
After I click ok, I get the error message:

`resolvconf-pull-resolved.service is a disabled or a static unit not running, not starting it.
cp: not writing through dangling symlink '/etc/resolvconf/resolv.conf.d/original'`

which I could not understand its meaning...

I then tried to follow the instructions here: https://www.ricmedia.com/set-permanent-dns-nameservers-ubuntu-debian-resolv-conf/

But I couldn't get the nameservers in the resolv.conf file. The only step in which I got a warning was when running
`sudo resolvconf -u`
which gave me
`/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf`

In any case, I can edit the resolv.conf file manually and change the nameservers, but I don't see any change in the reported behavior...

Regarding your suggestion to access via the IP address, I must clarify I'm trying to access a webpage in the intranet of my company.

Sorry if this is not an issue with openfortivpn, but I'm currently clueless about what's going on! :(

**Comment by rtargino** [comment]
@DimitriPapadopoulos , thanks a lot for you help, but I assume I'll give up and this thread may not be helpful to anyone in the future. After spending the whole day trying to figure out what was going on, it got clear it was a problem with the DNS.

The laptop I'm using is a Dell with RST which I had to do some work to install Ubuntu with dual boot (https://discourse.ubuntu.com/t/ubuntu-installation-on-computers-with-intel-r-rst-enabled/15347).

After changing the motherboard, the BIOS configuration changed, I couldn't boot into neither Windows nor Ubuntu but I managed to fix the Windows boot changing the BIOS settings again. Then somehow I lost GRUB. Then I installed it back and life was normal, until I stumbled upon this issue here.

I'll assume something along the way screwed up something and by now I don't care to find out exactly what's going on. I just changed the VPN client and (surprisingly) everything is working again.

Thanks for helping anyway! :)

**Comment by DimitriPapadopoulos** [comment]
You don't have to spend so much time on this issue or give up. I just needs a confirmation that this is a DNS problem, by comparing accessing a server by IP address vs. DNS name. I understand it is.

The problem is that _openfortivpn_ tries to use `resolvconf` when it is installed, as the promise of _resolvconf_ was to offer a unified API to modify DNS parameters, that would work whatever the back-end. Unfortunately:
* _systemd-resolved_, even when just installed and not enabled, includes a `resolvconf` commad that is broken by design as it does not support other backends,
* even the `resolvconf` command from the _resolvconf_ package might not work as expected when NetworkManager takes over.

The above problems are more acute on recent Fedora distributions but may be observed on other distributions, depending on the version of _openfortivpn_ and the packages installed. I use _openfortivpn_ myself on an Ubuntu 20.04 LTS workstation on a routine basis and it works. What might have changed from the previous setup is that you're using a different version of _openfoRtivpn_ and/or you have installed removed packages with an impact on DNS handling.

**Comment by DimitriPapadopoulos** [comment]
There are a few solutions you may try:
1. If you have compiled and installed _openfortivpn_ by yourself, configure with `--disable-resolvconf` and check whether it helps. Since you're using _openfortivpn_ 1.12.0 I suspect you're just using the current Ubuntu package.
2. Remove packages that ship a `resolvconf` broken by design, such as _systemd-resolvconfd_. I think that might have help on Fedora but is not necessarily on Ubuntu 20.04. Before attempting anything like that, try the last paragraph of this comment first and report back.
3. Use _NetworkManager_ instead of using _openfortivpn_ directly. That should work and is certainly the right thing to do when _NetworkManager_ is installed on your system. Unfortunately [there's an issue in _NetworkManager-fortisslvpn_](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/20) that took a very long time to get fixed. I'm not certain of the exact situation on Ubuntu 20.04, I don't have my Ubuntu 20.04 workstation with me right now.

You may start with finding which version of `resolvconf` you have in your path - there are different versions provided by different packages:
```
which resolvconf
dpkg -S `which resolvconf`
```

**Comment by DimitriPapadopoulos** [comment]
For what it's worth, on the Ubuntu 20.04 workstation I have access to:
* `resolvconf` is not available, neither from the _resolvconf_ package not from _systemd-resolved_. These two packages are not installed.
* _openfortivpn_ works just fine.
* I haven't tried _NetworkManager-fortisslvpn_.

```
$ dpkg -l | fgrep systemd-resolved
$ 
$ dpkg -l | fgrep resolvconf
$ 
$ which resolvconf
$ 
```

**Comment by bytewind** [comment]
I'm on the same boat, and get the same error, when I attempt to do a dpkg-reconfigure on resolvconf.

**Comment by DimitriPapadopoulos** [comment]
@byewind Avoid package `resolvconf` (I think it's not installed by default). What is the output of the following?
```
which resolvconf
dpkg -S `which resolvconf
```

**Comment by bytewind** [comment]
@DimitriPapadopoulos 

Hello! I logged off yesterday, but today it does work. It seems that although I got an error message after `dpkg reconfigure resolvconf` but appears that the symlink was successfully created.
