### ISSUE TITLE
Empty HDLC frames causing connection drops

### ISSUE THREAD

**Issue by nferch** [adrienverge/openfortivpn#788]
Version: 1.15.0 (built from git source)
OS: FreeBSD 11.4-RELEASE-p3
VPN: Unknown

Hi,

I'm seeing a strange issue where my connection will randomly drop. I've tracked it down to a problem that `hdlc_find_frame` https://github.com/adrienverge/openfortivpn/blob/master/src/hdlc.c#L198  has in parsing input buffers with empty HDLC frames at the end.

The function is passed the following input buffer with a `start` at byte 251:

```
0000000     0   7e ff 7d 23 7d 20 21 45 20 7d 20 34 7d 20 7d 20
0000010    16   40 7d 20 3f 7d 26 6d 8e 7d 2a d2 7d 36 8e ac 7d
0000020    32   30 7d 20 a6 d2 fd 7d 20 7d 36 61 e6 7f 22 7d 3b
0000030    48   de 6c 5b 80 7d 30 7d 27 f6 b1 dd 7d 20 7d 20 7d
0000040    64   21 7d 21 7d 28 7d 2a 7d 2c 27 8d 4a 44 23 d4 e8
0000050    80   56 7d 24 7e 7e ff 7d 23 7d 20 21 45 20 7d 20 34
0000060    96   7d 20 7d 20 40 7d 20 3f 7d 26 6d 8e 7d 2a d2 7d
0000070   112   36 8e ac 7d 30 7d 20 a6 d2 fd 7d 20 7d 36 61 e6
0000080   128   7f 22 7d 3b de 6d 7d 3f 80 7d 30 7d 27 f3 b1 7d
0000090   144   3c 7d 20 7d 20 7d 21 7d 21 7d 28 7d 2a 7d 2c 27
00000a0   160   8d 4a 44 23 d4 e8 b8 7f 7e 7e ff 7d 23 7d 20 21
00000b0   176   45 20 7d 20 34 7d 20 7d 20 40 7d 20 3f 7d 26 6d
00000c0   192   8e 7d 2a d2 7d 36 8e ac 7d 30 7d 20 a6 d2 fd 7d
00000d0   208   20 7d 36 61 e6 7f 22 7d 3b de 6d 93 80 7d 30 7d
00000f0   224   27 fe b0 9d 7d 20 7d 20 7d 21 7d 21 7d 28 7d 2a
0000100   240   7d 2c 27 8d 4a 44 23 d4 e8 d6 57 7e 7e ff
```

I've worked around the problem by inserting the following code before the final return https://github.com/adrienverge/openfortivpn/blob/master/src/hdlc.c#L227:

```
if (e - s == 0) {
        log_error("empty hdlc frame! %d %d\n", s,  *origstart);
        do_log_packet("  (hex) ", bufsize, buffer);                                                                                 
        return ERR_HDLC_NO_FRAME_FOUND;
}
```

I'm not sure what the desired behavior is supposed to be, or if the function is supposed to receive input buffers in this manner (i.e. if the bug is somewhere higher in the stack). I will continue to monitor how well this change addresses my problem, but any help or similar experiences would be appreciated!

**Comment by DimitriPapadopoulos** [comment]
Ah, I do hope this is not an effect of 32f1949, where I reverted our previous HDLC code to the sample HDLC code from RFC 1662 and tried to change initialization of static variables to something compatible with option `--persistent`. How often do you see these connection drops? Are you using `--persistent`? Actually which options do you pass `openfortivpn`? If relevant could you try without `--persistent`? Perhaps even try to revert 32f1949 (but again without `--persistent`).

If all the above fails, I could look into the logic of `hdlc_find_frame` and calling function `pppd_read` - but I don't have much time at my disposal right now.

That said FreeBSD hasn't been tested that much I'm afraid, so it could be something else. Perhaps it could help if you could test _openfortivpn_ in the exact same context but with Linux instead of FreeBSD (a virtual machine should do).

**Comment by DimitriPapadopoulos** [comment]
Byte 251 starts the sequence `7e 7e ff` at the end of the buffer. According to RFC 1662, the first `7e` is the Flag Sequence that ends the HDLC frame, while `7e ff` is the Flag Sequence followed by Address Field that starts the next HDLC frame. I don't see anything wrong in the buffer contents, at least the end of the buffer. Note that the buffer contents end exactly where the next HDLC frame starts, but this is supposed to be handled gracefully. Will have to look into it...

**Comment by nferch** [comment]
Thanks for the context and insight, it's really helpful. My suspicion is that it's some odd interaction between some FreeBSD-specific code and the HDLC parsing given how few people seem to be having the problem. I haven't been able to reproduce on Linux or Mac OS X, which is the most similar to FreeBSD.

The frequency is pretty random, many times it happens a few minutes after connections are established, sometimes it takes hours for it to occur.

I'm not too familiar with `--persistent`, but I'm not sure if it would help. When `hdlc_find_frame` was encountering the empty frame it was returning an empty size which was causing the `if (frmsize < 5)` check in `hdlc_decode` to fully terminate the connection.

I'll try reverting https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae and see if that helps. If not, my quick hack seems to be working well, but I'm still curious of the root cause.

**Comment by nferch** [comment]
I've been running with https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae reverted for a few days ago and it's been much more stable. I see occasional `SYS_ERROR_SYSCALL`/`ERR_SSL_EOF`/Protocol violation with EOF errors but they don't seem to happen at the same frequency or time as the other errors.

**Comment by DimitriPapadopoulos** [comment]
Not much to do on your side. I want to feed _hdlc_find_frame()_ the buffer you have initially sent us to better understand. Perhaps I can better understand this issue. Just don't have much time right now.

Also I don't see how 32f1949 could be the culprit after looking at it more closely. As you, I suspect it might be a change in a calling function. If you have time, perhaps you can look in this direction and find which commit could be responsible - here I suppose a relatively recent commit is responsible since you wrote that it used to work before 32f1949.

**Comment by nferch** [comment]
To be clear, I reverted https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae and https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae only, I didn't back-out any other commits between that and master.

I'll see what I can do with looking at `pppd_read`, although I don't have any real sense of what normal should be there.

**Comment by DimitriPapadopoulos** [comment]
OK, I see. Suggestions:
* Revert 32f1949 in smaller multiple steps, perhaps we can find which exact smaller change breaks _openfortivpn_.
* We also need to feed the sample buffer you have provided to _hdlc_find_frame()_, with and without 32f1949. Does 32f1949 make any difference?

**Comment by DimitriPapadopoulos** [comment]
Just to make sure I understand: Can you confirm that reverting 32f1949 fixes the issue you are reporting?

**Comment by nferch** [comment]
@DimitriPapadopoulos sorry for the delay on this. Over the last weeks I have been unable to reproduce this error with or without https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae applied. I'm wondering if something changed on the other end.

Will continue to monitor this and look into if something else on my end has changed.

**Comment by mr0mr0** [comment]
Version: 1.19.0 (FreeBSD pkg install)
OS: 13.1-RELEASE-p6 and earlier
VPN: workplace fortigate

Hi,

I had the same error, and same random occurrence. It was killing my escape from Ubuntu to FreeBSD for "work from home".

Following the clues here I think the problem is the limit (i < bufsize - 2) used in two loops: "Look for frame start" and "Discard empty frames" in hdlc_find_frame().

As nferch found, when 0x7e is present at (bufsize-3) and (bufsize-2) then we get e=s and a zero length frame is returned causing fatal HDLC invalid frame.

Both loops work better with condition (i < bufsize). All 0x7e bytes are found and handled normally - no need to stop at (bufsize - 3). I must say I very much appreciate the clean lines of that code, and the way a partial frame is handled along with its opening 0x7e.

I have been running with this modification for over a week without any drops. Previously it was dropping several times every day.

The version on Ubuntu which had no drops was 1.17.1
I have not been using --persistent on Ubuntu or FreeBSD

.openfortivpn console output fragment
----
INFO:   Tunnel is up and running.
ERROR:  Failed to decode PPP packet from HDLC frame (invalid frame).
INFO:   Cancelling threads...
----

The code I've been running in the last week had cruft not shown in the diff below - hopefully removing it made no difference

=======
diff --git a/src/hdlc.c b/src/hdlc.c
index 3b2c8ac..7fa19c8 100644
--- a/src/hdlc.c
+++ b/src/hdlc.c
@@ -200,7 +200,7 @@ ssize_t hdlc_find_frame(const uint8_t *buffer, size_t bufsize, off_t *start)
        int i, s = -1, e = -1;
 
        // Look for frame start
-       for (i = *start; i < bufsize - 2; i++) {
+       for (i = *start; i < bufsize ; i++) {
                if (buffer[i] == 0x7e) { // Flag Sequence
                        s = i + 1;
                        break;
@@ -210,7 +210,7 @@ ssize_t hdlc_find_frame(const uint8_t *buffer, size_t bufsize, off_t *start)
                return ERR_HDLC_NO_FRAME_FOUND;
 
        // Discard empty frames
-       while (s < bufsize - 2 && buffer[s] == 0x7e) // consecutive Flag Sequences
+       while (s < bufsize && buffer[s] == 0x7e) // consecutive Flag Sequences
                s++;
 
        // Look for frame end
=======

**Comment by DimitriPapadopoulos** [comment]
These `-2` have been there for ever, so I have never questioned them.

Also, this tends to confirm https://github.com/adrienverge/openfortivpn/commit/32f1949ffb78b9b7e447bff8ddd51bb7b58995ae is unrelated. This is a relief, as I was unable to find an error in that commit, despite my efforts.

**Comment by DimitriPapadopoulos** [comment]
I've played around with the following piece of code: I'm feeding [hdlc_find_frame](https://github.com/adrienverge/openfortivpn/blob/913ff9770ed46054f5de35b0dd2212d9aa0a8376/src/hdlc.c#L198-L228) the buffer provided by @nferch, starting at byte 251 so that it has only the 3 bytes `7e 7e ff` to process. Without the patch, it returns 0 (empty HDLC frame) instead of `ERR_HDLC_NO_FRAME_FOUND`.

<details>
<summary>my test code</summary>

```c
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>

#define ERR_HDLC_NO_FRAME_FOUND		-2


ssize_t hdlc_find_frame(const uint8_t *buffer, size_t bufsize, off_t *start)
{
	int i, s = -1, e = -1;

	// Look for frame start
	for (i = *start; i < bufsize - 2; i++) {
		if (buffer[i] == 0x7e) { // Flag Sequence
			s = i + 1;
			break;
		}
	}
	if (s == -1)
		return ERR_HDLC_NO_FRAME_FOUND;

	// Discard empty frames
	while (s < bufsize - 2 && buffer[s] == 0x7e) // consecutive Flag Sequences
		s++;

	// Look for frame end
	for (i = s; i < bufsize; i++) {
		if (buffer[i] == 0x7e) { // Flag Sequence
			e = i;
			break;
		}
	}
	if (e == -1)
		return ERR_HDLC_NO_FRAME_FOUND;

	*start = s;
	return e - s;
}


static const uint8_t buffer[] = {
	0x7e, 0xff, 0x7d, 0x23, 0x7d, 0x20, 0x21, 0x45, 0x20, 0x7d, 0x20, 0x34, 0x7d, 0x20, 0x7d, 0x20,  //   0 -  15
	0x40, 0x7d, 0x20, 0x3f, 0x7d, 0x26, 0x6d, 0x8e, 0x7d, 0x2a, 0xd2, 0x7d, 0x36, 0x8e, 0xac, 0x7d,  //  16 -  31
	0x30, 0x7d, 0x20, 0xa6, 0xd2, 0xfd, 0x7d, 0x20, 0x7d, 0x36, 0x61, 0xe6, 0x7f, 0x22, 0x7d, 0x3b,  //  32 -  47
	0xde, 0x6c, 0x5b, 0x80, 0x7d, 0x30, 0x7d, 0x27, 0xf6, 0xb1, 0xdd, 0x7d, 0x20, 0x7d, 0x20, 0x7d,  //  48 -  63
	0x21, 0x7d, 0x21, 0x7d, 0x28, 0x7d, 0x2a, 0x7d, 0x2c, 0x27, 0x8d, 0x4a, 0x44, 0x23, 0xd4, 0xe8,  //  64 -  79
	0x56, 0x7d, 0x24, 0x7e, 0x7e, 0xff, 0x7d, 0x23, 0x7d, 0x20, 0x21, 0x45, 0x20, 0x7d, 0x20, 0x34,  //  80 -  95
	0x7d, 0x20, 0x7d, 0x20, 0x40, 0x7d, 0x20, 0x3f, 0x7d, 0x26, 0x6d, 0x8e, 0x7d, 0x2a, 0xd2, 0x7d,  //  96 - 111
	0x36, 0x8e, 0xac, 0x7d, 0x30, 0x7d, 0x20, 0xa6, 0xd2, 0xfd, 0x7d, 0x20, 0x7d, 0x36, 0x61, 0xe6,  // 112 - 127
	0x7f, 0x22, 0x7d, 0x3b, 0xde, 0x6d, 0x7d, 0x3f, 0x80, 0x7d, 0x30, 0x7d, 0x27, 0xf3, 0xb1, 0x7d,  // 128 - 143
	0x3c, 0x7d, 0x20, 0x7d, 0x20, 0x7d, 0x21, 0x7d, 0x21, 0x7d, 0x28, 0x7d, 0x2a, 0x7d, 0x2c, 0x27,  // 144 - 159
	0x8d, 0x4a, 0x44, 0x23, 0xd4, 0xe8, 0xb8, 0x7f, 0x7e, 0x7e, 0xff, 0x7d, 0x23, 0x7d, 0x20, 0x21,  // 160 - 175
	0x45, 0x20, 0x7d, 0x20, 0x34, 0x7d, 0x20, 0x7d, 0x20, 0x40, 0x7d, 0x20, 0x3f, 0x7d, 0x26, 0x6d,  // 176 - 191
	0x8e, 0x7d, 0x2a, 0xd2, 0x7d, 0x36, 0x8e, 0xac, 0x7d, 0x30, 0x7d, 0x20, 0xa6, 0xd2, 0xfd, 0x7d,  // 192 - 207
	0x20, 0x7d, 0x36, 0x61, 0xe6, 0x7f, 0x22, 0x7d, 0x3b, 0xde, 0x6d, 0x93, 0x80, 0x7d, 0x30, 0x7d,  // 208 - 223
	0x27, 0xfe, 0xb0, 0x9d, 0x7d, 0x20, 0x7d, 0x20, 0x7d, 0x21, 0x7d, 0x21, 0x7d, 0x28, 0x7d, 0x2a,  // 224 - 239
	0x7d, 0x2c, 0x27, 0x8d, 0x4a, 0x44, 0x23, 0xd4, 0xe8, 0xd6, 0x57, 0x7e, 0x7e, 0xff,              // 240 - 253
};


int main() {
    off_t start = 0;
	ssize_t offset = hdlc_find_frame(buffer, sizeof(buffer), &start);
    printf("offset = %ld\n", offset);
}
```
</details>

Thinking about it again, why stop processing the buffer two bytes before the end? I can see that this is an optimisation, as a new buffer would need at least two bytes `7e ff` for the start of the HDLC frame and one byte `7e` for the end of the HDLC frame. But then we need to handle the special case where `start` is precisely in these last bytes we skip.

The proposed solution results in the simplest code.
