### ISSUE TITLE
Error when using path in host parameter

### ISSUE THREAD

**Issue by gabrielef** [adrienverge/openfortivpn#789]
I'm having login issue when the host parameter contains a path, for example with config file:

`host = vpn.mydomain.com/tunnel`

I'm always receiving this error:

```
ERROR:  getaddrinfo: nodename nor servname provided, or not known
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

I have many other vpn without path that are correctly working.

Is related to the slash character that need to be escaped?

Thanks
Gabriele

**Comment by DimitriPapadopoulos** [comment]
That's because the host parameter cannot contain a path, just a host name.

Why are you attempting something like this?

**Comment by gabrielef** [comment]
Hi @DimitriPapadopoulos,
because this is the configuration I received for vpn connection.

The FortiClient GUI seems to handle the path, this is why i tried adding it in configuration file.

Using the host without path is a different vpn connection, I don't know if this is a bad practice but in my case is mandatory to use it.

**Comment by DimitriPapadopoulos** [comment]
_openfortivpn_ currently expects a host name, so I'm afraid this is expected to fail.

I wasn't aware of the possibility to add a path - probably [SSL VPN multi-realm](https://docs.fortinet.com/document/fortigate/6.4.2/administration-guide/724772/ssl-vpn-multi-realm). As far as I can see [SSL VPN multi-realm](https://docs.fortinet.com/document/fortigate/6.2.0/cookbook/724772/ssl-vpn-multi-realm) is a FortiOS 6.2.0 addition. Perhaps @mrbaseman who has experience setting up FortiGate appliances can shed more light.

Since we already have `host` and `port` options in the config file, it would make sense to add a **`realm`** option. Also we already accept `hostname:port` as a command line argument, this could be extended to `hostname:port/realm`. 
Can you show us a screen capture of the FortiClient GUI just before entering the host name with path? I just want to see what the GUI looks like, what the field names are.

**Comment by gabrielef** [comment]
![FortiClient -- The Security Fabric Agent](https://user-images.githubusercontent.com/2587166/96226122-735c4200-0f92-11eb-879d-8a41eef4cb83.png)

**Comment by DimitriPapadopoulos** [comment]
I see. The field name **gateway** in FortiClient is more easily understood as `vpn.mydomain.com/realm` than **host** in the _openfortivpn_ config file. Yet both are possible:
- extend the `host` option to accept `VPN.mydomain.com/realm`, but then perhaps it should be renamed to `gateway` (keeping `host` as a synonym for compatibility),
- add an additional `realm` option.

Opinions?

**Comment by gabrielef** [comment]
Hi @DimitriPapadopoulos,

I have just tried using `realm` in config file and it's working!

**Comment by gabrielef** [comment]
Update: the vpn connection is up and running but I'm not able to reach servers.

**Comment by DimitriPapadopoulos** [comment]
I had actually never noticed this `realm` option introduced in f9c767d and was preparing to implement it. In my defence the implementation looks incomplete to me. The current syntax is:
```
Usage: openfortivpn [<host>[:<port>]]
```
In addition to the `--realm` parameter and the `realm` option of the config file, the syntax could be extended to match the FortiOS documentation:
```
Usage: openfortivpn [<host>[:<port>][/realm]]
```
