### ISSUE TITLE
Backup hosts

### ISSUE THREAD

**Issue by FacundoAcevedo** [adrienverge/openfortivpn#790]
I think it could be a nice feature to be able to define some backup hosts, so when the first is not reachable try the second and so on.

**Comment by DimitriPapadopoulos** [comment]
Isn't this reasonably easy to implement in a script  if you're using _openfortivpn_ from the command line, or in NetworkManager if using NetworkManager?

I'm asking because I try to avoid bloatware. If something can be easily implemented in a script, why add 50 lines of C code to obtain the same result? Especially in this case the C code would not provide extra functionality as far as I can see, because you need to re-authenticate anyway. I have found out this is not the case with `--persistent`, it actually does add new functionality: it could be implemented as "authenticate once, then try to restart the tunnel multiple times using the credential (cookie) sent during authentication".

Perhaps we could provide sample scripts to achieve such tasks.

**Comment by FacundoAcevedo** [comment]
Yes,  it is definitely bloatware here, I have opened the same issue in the [NM repo](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/34).

Thanks :D
