### ISSUE TITLE
openfortivpn: vpn not working

### ISSUE THREAD

**Issue by sant527** [adrienverge/openfortivpn#805]
I am able to authenticate and connect 

![image](https://user-images.githubusercontent.com/6462531/97946556-d3cfe980-1db0-11eb-8eba-e70d39b1fd0d.png)

But if i check my ip address in https://whatismyipaddress.com/ it does not change.

And certain things which i can access only using vpn are just in hang

I able to ping the local ip address
![image](https://user-images.githubusercontent.com/6462531/97946728-3cb76180-1db1-11eb-8343-26099d8b7da8.png)

but not to the remote ip

how to know the vpn is working and how to access things

**Comment by DimitriPapadopoulos** [comment]
Not sure what happens here, but from what I gather here:
* It looks like the VPN tunnel is established.
* You cannot route traffic through the tunnel as expected. 

I believe the first step does work, but then _openfortivpn_ might be unable to change routing and DNS parameters for some reason. In this specific case it's more of a routing issue since you're experiencing problems even when using IP addresses. Which exact Linux distribution is this, which version? Can you check routing before/after starting _openfortivpnn_? Use `route` for example.

It would help if you could post text instead of screen captures, since this is not a graphical interface. You should of course sanitize everything like you already do. However I suggest you do not erase sanitized items, instead change them to a different, unique and consistent value throughout the ticket. For example for IP addresses, values such as `xxx.xxx.xxx.xxx` are OK, as long as there's a one to one mapping between the real address and the sanitized value.

**Comment by DimitriPapadopoulos** [comment]
The _Cannot determine ethernet address for proxy ARP_ message is probably related to the issues you're expriencing. Perhaps you can fix it first - run a query with this message in whatever search engine you like.

Have you in any way modified anything under `/etc/ppp` on this computer?

What is the network context here? Are you at home, connected to you ISP box through Wi-Fi ? Have you in any way modified the default network configuration of your computer?

**Comment by DimitriPapadopoulos** [comment]
Were you able to fix this problem?

**Comment by sant527** [comment]
No. I left using it
