### ISSUE TITLE
diagnostic message colors invisible in gnome-terminal

### ISSUE THREAD

**Issue by RBKreckel** [adrienverge/openfortivpn#85]
I just discovered that OpenFortiVPN actually prints diagnostic messages, not just some gratuitous empty lines! The problem is that these diagnostic messages are hardly visible in gnome-terminal in the standard light system theme. Here is a screenshot.
![openfortivpn-in-gnome-terminal](https://cloud.githubusercontent.com/assets/24757097/21605817/c7da3428-d1ab-11e6-8b73-e40ed54c399a.png)

**Comment by adrienverge** [comment]
Hi @RBKreckel,

I also have a light-background theme but I clearly see the debug lines in gnome-terminal:
![gnome-terminal](https://cloud.githubusercontent.com/assets/5244945/22325454/631c72a2-e3ae-11e6-8c46-33e85424a409.png)

I believe this is a problem with your current theme, because `\033[0;90m` colors (the ones used for `log_debug`) are meant to be seen. All standard light themes I have in gnome-terminal (black on white, black on light yellow, solarized light) display it correctly.

You could try to use one of those standard themes, or keep the one you have but go to Edit > Profile > Colors and change the 9th one of the palette (the one at bottom left) to something more contrasted with your background.

Hope this helps!

**Comment by adrienverge** [comment]
Forget my previous message, I thought you were talking about debug messages, not info ones!

This is actually an issue. Will fix it.

**Comment by RBKreckel** [comment]
Great. Thanks!
