### ISSUE TITLE
Reconsider #747

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#871]
After applying #747, the password is overwritten in one of the processes only. Its still appears in the other process:
```
$ ps aux | fgrep openfortivpn
root       51616  0.0  0.0  14876  4644 pts/0    S+   14:43   0:00 sudo /opt/bin/openfortivpn -c /opt/etc/openfortivpn/config -p 0123456789AB
root       51617  0.1  0.0 375452  6036 pts/0    Sl+  14:43   0:00 /opt/bin/openfortivpn -c /opt/etc/openfortivpn/config -p ************
```

Can we fix that?

**Comment by mrbaseman** [comment]
Well, using the `-p` option already triggers a warning. I'd argue that this is enough, and as a bonus, since #747 we wipe out the content in memory if the users supply their password on the command line despite of this warning. 

Having the password in the config file is at least better than on the command line. However, we can remove this from the examples, since it is not absolutely needed. If there is no password in the config nor on the command line, there will be an interactive prompt (which isn't the most comfortable solution but the safest one compared to the alternatives that I have mentioned so far, `pinentry` is even better, but that's a discussion in #710 )

I would avoid messing around in the memory allocated by argv of other processes (i.e. the sudo process in this case) - even if we could do so when running as root. It's simply bad practice. The user should avoid providing sensitive information on the command line.

**Comment by DimitriPapadopoulos** [comment]
Yes, I agree. I will close this issue with "wontfix" but wanted to have a discussion first.

Perhaps the lesson of all this is that adding a paragraph on `pinentry` in the README is agood idea.

**Comment by DimitriPapadopoulos** [comment]
I think #872 addresses this issue brilliantly...
