### ISSUE TITLE
Fails to connect with no error message

### ISSUE THREAD

**Issue by k-caps** [adrienverge/openfortivpn#954]
When trying to connect to vpn while another VPN is active, openfortigui tries to connect and can't. A simple error message along the lines of "Can't access VPN settings, maybe it is in use by another program" would be very helpful.

**Comment by DimitriPapadopoulos** [comment]
You may report OpenFortiGUI issues here: https://github.com/theinvisible/openfortigui

**Comment by DimitriPapadopoulos** [comment]
Besides `openfortivpn` itself **can** connect to a VPN when another VPN is active, **if** the active VPN allows it. Some organizations may not allow to start a VPN from their networks and will just silently block attempts. I am not saying that routing and DNS will be handled correctly in such a case - for example the VPNs might push conflicting routing instructions. However, the second tunnel should be started.

You need to identify more precisely what is going wrong in your case. Using `openfortivpn` from the command line might help. Provide logs (sanitized if needed) otherwise we cannot understand, reproduce or fix the issue at hand.
