### ISSUE TITLE
how to get trusted_cert from command

### ISSUE THREAD

**Issue by benzdeus** [adrienverge/openfortivpn#995]
i need use with gitlab ci but trusted_cert change every push mycode

**Comment by fabianonunes** [comment]
It's weird that it's changing every time. Maybe a load balancer?

You can get trusted_cert with command:

```bash
echo | openssl s_client -connect $ip_or_domain:$port 2>/dev/null | \
  openssl x509 -outform der | \
  sha256sum | \
  awk '{ print $1 }'
```

If SNI is enabled on the server, you must use the domain instead of the IP.

But you shouldn't blindly trust a server certificate. Maybe you could add the CA cert to the system's certificate store (`man update-ca-certificates`  for more info)

**Comment by benzdeus** [comment]
> 



> It's weird that it's changing every time. Maybe a load balancer?
> 
> You can get trusted_cert with command:
> 
> ```shell
> echo | openssl s_client -connect $ip_or_domain:$port 2>/dev/null | \
>   openssl x509 -outform der | \
>   sha256sum | \
>   awk '{ print $1 }'
> ```
> 
> If SNI is enabled on the server, you must use the domain instead of the IP.
> 
> But you shouldn't blindly trust a server certificate. Maybe you could add the CA cert to the system's certificate store (`man update-ca-certificates` for more info)

thank bro.

**Comment by gunter423** [comment]
Sample example:

```bash
trusted_cert=$(echo | openssl s_client -connect ip:port 2>/dev/null | openssl x509 -outform der | sha256sum | awk '{ print $1 }')
openfortivpn -c /etc/openfortivpn/config --trusted-cert $trusted_cert
```

Have a nice day 😉
